// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum ClientState {
  unknown,
  resetting,
  unsupported,
  unauthorized,
  poweredOff,
  poweredOn,
}

enum ConnectionState {
  disconnected,
  connecting,
  reconnecting,
  connected,
  disconnecting,
}

enum AttResult {
  success,
  invalidHandle,
  readNotPermitted,
  writeNotPermitted,
  invalidOffset,
  attributeNotFound,
  unlikelyError,
}

/// A unique identifier for a peripheral coupled with the [adapterIdentifier] and
/// [clientIdentifier] that discovered it.
///
/// The [clientIdentifier] is the identifier of the client that discovered the
/// peripheral. This is useful when multiple clients are connected to the same
/// adapter. If omitted, the default client is used.
///
/// The [adapterIdentifier] is the identifier of the adapter that discovered the
/// peripheral. This is useful when multiple adapters are available on the same
/// device. If omitted, the default adapter is used.
class ClientSession {
  ClientSession({
    this.peripheralIdentifier,
    this.clientIdentifier,
    this.adapterIdentifier,
    this.restorationIdentifier,
  });

  String? peripheralIdentifier;

  String? clientIdentifier;

  String? adapterIdentifier;

  String? restorationIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static ClientSession decode(Object result) {
    result as List<Object?>;
    return ClientSession(
      peripheralIdentifier: result[0] as String?,
      clientIdentifier: result[1] as String?,
      adapterIdentifier: result[2] as String?,
      restorationIdentifier: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ClientSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PeripheralSession {
  PeripheralSession({
    required this.peripheralIdentifier,
    this.clientIdentifier,
    this.adapterIdentifier,
    this.restorationIdentifier,
  });

  String peripheralIdentifier;

  String? clientIdentifier;

  String? adapterIdentifier;

  String? restorationIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeripheralSession decode(Object result) {
    result as List<Object?>;
    return PeripheralSession(
      peripheralIdentifier: result[0]! as String,
      clientIdentifier: result[1] as String?,
      adapterIdentifier: result[2] as String?,
      restorationIdentifier: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeripheralSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PeripheralManagerSession {
  PeripheralManagerSession({
    this.clientIdentifier,
    this.adapterIdentifier,
    this.restorationIdentifier,
  });

  String? clientIdentifier;

  String? adapterIdentifier;

  String? restorationIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeripheralManagerSession decode(Object result) {
    result as List<Object?>;
    return PeripheralManagerSession(
      clientIdentifier: result[0] as String?,
      adapterIdentifier: result[1] as String?,
      restorationIdentifier: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeripheralManagerSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Peripheral {
  Peripheral({
    required this.session,
    this.name,
    this.rssi,
    required this.state,
  });

  PeripheralSession session;

  String? name;

  int? rssi;

  ConnectionState state;

  List<Object?> _toList() {
    return <Object?>[
      session,
      name,
      rssi,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static Peripheral decode(Object result) {
    result as List<Object?>;
    return Peripheral(
      session: result[0]! as PeripheralSession,
      name: result[1] as String?,
      rssi: result[2] as int?,
      state: result[3]! as ConnectionState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Peripheral || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AdvertisementData {
  AdvertisementData({
    this.localName,
    this.manufacturerData,
    this.serviceUuids,
    this.serviceData,
    this.txPowerLevel,
    this.isConnectable,
  });

  String? localName;

  Uint8List? manufacturerData;

  List<String?>? serviceUuids;

  Map<String?, Uint8List?>? serviceData;

  int? txPowerLevel;

  bool? isConnectable;

  List<Object?> _toList() {
    return <Object?>[
      localName,
      manufacturerData,
      serviceUuids,
      serviceData,
      txPowerLevel,
      isConnectable,
    ];
  }

  Object encode() {
    return _toList();  }

  static AdvertisementData decode(Object result) {
    result as List<Object?>;
    return AdvertisementData(
      localName: result[0] as String?,
      manufacturerData: result[1] as Uint8List?,
      serviceUuids: (result[2] as List<Object?>?)?.cast<String?>(),
      serviceData: (result[3] as Map<Object?, Object?>?)?.cast<String?, Uint8List?>(),
      txPowerLevel: result[4] as int?,
      isConnectable: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdvertisementData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ScanResult {
  ScanResult({
    required this.peripheral,
    required this.advertisementData,
  });

  Peripheral peripheral;

  AdvertisementData advertisementData;

  List<Object?> _toList() {
    return <Object?>[
      peripheral,
      advertisementData,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanResult decode(Object result) {
    result as List<Object?>;
    return ScanResult(
      peripheral: result[0]! as Peripheral,
      advertisementData: result[1]! as AdvertisementData,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Service {
  Service({
    required this.uuid,
    this.isPrimary = false,
  });

  String uuid;

  bool isPrimary;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      isPrimary,
    ];
  }

  Object encode() {
    return _toList();  }

  static Service decode(Object result) {
    result as List<Object?>;
    return Service(
      uuid: result[0]! as String,
      isPrimary: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Service || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Characteristic {
  Characteristic({
    required this.uuid,
    this.value,
    this.descriptors,
    this.properties,
  });

  String uuid;

  Uint8List? value;

  List<Descriptor?>? descriptors;

  CharacteristicProperty? properties;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      value,
      descriptors,
      properties,
    ];
  }

  Object encode() {
    return _toList();  }

  static Characteristic decode(Object result) {
    result as List<Object?>;
    return Characteristic(
      uuid: result[0]! as String,
      value: result[1] as Uint8List?,
      descriptors: (result[2] as List<Object?>?)?.cast<Descriptor?>(),
      properties: result[3] as CharacteristicProperty?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Characteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Descriptor {
  Descriptor({
    required this.uuid,
    this.value,
  });

  String uuid;

  Uint8List? value;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static Descriptor decode(Object result) {
    result as List<Object?>;
    return Descriptor(
      uuid: result[0]! as String,
      value: result[1] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Descriptor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class CharacteristicProperty {
  CharacteristicProperty({
    this.broadcast = false,
    this.read = false,
    this.writeWithoutResponse = false,
    this.write = false,
    this.notify = false,
    this.indicate = false,
    this.authenticatedSignedWrites = false,
    this.extendedProperties = false,
    this.notifyEncryptionRequired = false,
    this.indicateEncryptionRequired = false,
  });

  bool broadcast;

  bool read;

  bool writeWithoutResponse;

  bool write;

  bool notify;

  bool indicate;

  bool authenticatedSignedWrites;

  bool extendedProperties;

  bool notifyEncryptionRequired;

  bool indicateEncryptionRequired;

  List<Object?> _toList() {
    return <Object?>[
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ];
  }

  Object encode() {
    return _toList();  }

  static CharacteristicProperty decode(Object result) {
    result as List<Object?>;
    return CharacteristicProperty(
      broadcast: result[0]! as bool,
      read: result[1]! as bool,
      writeWithoutResponse: result[2]! as bool,
      write: result[3]! as bool,
      notify: result[4]! as bool,
      indicate: result[5]! as bool,
      authenticatedSignedWrites: result[6]! as bool,
      extendedProperties: result[7]! as bool,
      notifyEncryptionRequired: result[8]! as bool,
      indicateEncryptionRequired: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CharacteristicProperty || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class CharacteristicPermission {
  CharacteristicPermission({
    this.readable = false,
    this.writeable = false,
    this.readEncryptionRequired = false,
    this.writeEncryptionRequired = false,
  });

  bool readable;

  bool writeable;

  bool readEncryptionRequired;

  bool writeEncryptionRequired;

  List<Object?> _toList() {
    return <Object?>[
      readable,
      writeable,
      readEncryptionRequired,
      writeEncryptionRequired,
    ];
  }

  Object encode() {
    return _toList();  }

  static CharacteristicPermission decode(Object result) {
    result as List<Object?>;
    return CharacteristicPermission(
      readable: result[0]! as bool,
      writeable: result[1]! as bool,
      readEncryptionRequired: result[2]! as bool,
      writeEncryptionRequired: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CharacteristicPermission || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AttRequest {
  AttRequest({
    required this.requestId,
    required this.centralIdentifier,
    required this.characteristicUuid,
    required this.serviceUuid,
    this.offset = 0,
    this.value,
  });

  int requestId;

  String centralIdentifier;

  String characteristicUuid;

  String serviceUuid;

  int offset;

  Uint8List? value;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      centralIdentifier,
      characteristicUuid,
      serviceUuid,
      offset,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttRequest decode(Object result) {
    result as List<Object?>;
    return AttRequest(
      requestId: result[0]! as int,
      centralIdentifier: result[1]! as String,
      characteristicUuid: result[2]! as String,
      serviceUuid: result[3]! as String,
      offset: result[4]! as int,
      value: result[5] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MutableDescriptor {
  MutableDescriptor({
    required this.uuid,
    this.value,
  });

  String uuid;

  Uint8List? value;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableDescriptor decode(Object result) {
    result as List<Object?>;
    return MutableDescriptor(
      uuid: result[0]! as String,
      value: result[1] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableDescriptor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MutableCharacteristic {
  MutableCharacteristic({
    required this.uuid,
    this.properties,
    this.permissions,
    this.value,
    this.descriptors,
  });

  String uuid;

  CharacteristicProperty? properties;

  CharacteristicPermission? permissions;

  Uint8List? value;

  List<MutableDescriptor?>? descriptors;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      properties,
      permissions,
      value,
      descriptors,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableCharacteristic decode(Object result) {
    result as List<Object?>;
    return MutableCharacteristic(
      uuid: result[0]! as String,
      properties: result[1] as CharacteristicProperty?,
      permissions: result[2] as CharacteristicPermission?,
      value: result[3] as Uint8List?,
      descriptors: (result[4] as List<Object?>?)?.cast<MutableDescriptor?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableCharacteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MutableService {
  MutableService({
    required this.uuid,
    this.isPrimary = true,
    required this.characteristics,
  });

  String uuid;

  bool isPrimary;

  List<MutableCharacteristic?> characteristics;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      isPrimary,
      characteristics,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableService decode(Object result) {
    result as List<Object?>;
    return MutableService(
      uuid: result[0]! as String,
      isPrimary: result[1]! as bool,
      characteristics: (result[2]! as List<Object?>).cast<MutableCharacteristic?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableService || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ClientState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ConnectionState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AttResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is ClientSession) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PeripheralSession) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PeripheralManagerSession) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is Peripheral) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is AdvertisementData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ScanResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is Service) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is Characteristic) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is Descriptor) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is CharacteristicProperty) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is CharacteristicPermission) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is AttRequest) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is MutableDescriptor) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is MutableCharacteristic) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is MutableService) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ClientState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConnectionState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AttResult.values[value];
      case 132:
        return ClientSession.decode(readValue(buffer)!);
      case 133:
        return PeripheralSession.decode(readValue(buffer)!);
      case 134:
        return PeripheralManagerSession.decode(readValue(buffer)!);
      case 135:
        return Peripheral.decode(readValue(buffer)!);
      case 136:
        return AdvertisementData.decode(readValue(buffer)!);
      case 137:
        return ScanResult.decode(readValue(buffer)!);
      case 138:
        return Service.decode(readValue(buffer)!);
      case 139:
        return Characteristic.decode(readValue(buffer)!);
      case 140:
        return Descriptor.decode(readValue(buffer)!);
      case 141:
        return CharacteristicProperty.decode(readValue(buffer)!);
      case 142:
        return CharacteristicPermission.decode(readValue(buffer)!);
      case 143:
        return AttRequest.decode(readValue(buffer)!);
      case 144:
        return MutableDescriptor.decode(readValue(buffer)!);
      case 145:
        return MutableCharacteristic.decode(readValue(buffer)!);
      case 146:
        return MutableService.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The APIs that are used to communicate from the flutter plugin to the
/// host platform.
class ButaneHostApi {
  /// Constructor for [ButaneHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ButaneHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// "Central" APIs.
  Future<ClientState> state({ClientSession? session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.state$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ClientState;
  }

  /// Scans for peripherals that are advertising services.
  Future<void> scan({ClientSession? session, List<String>? forServices}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.scan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, forServices]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelScan({ClientSession? session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// A list of known peripherals optionally filtered by their identifiers.
  Future<List<Peripheral>> peripherals({ClientSession? session, List<String> peripheralIdentifiers = const []}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripherals$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, peripheralIdentifiers]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Peripheral>();
  }

  /// A list of connected peripherals identified by an offered service.
  Future<List<Peripheral>> connectedPeripherals({ClientSession? session, List<String> serviceUuids = const []}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectedPeripherals$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Peripheral>();
  }

  /// Establishes a connection to the peripheral.
  Future<void> connect({required PeripheralSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Cancels an active or pending connection to the peripheral.
  Future<void> cancelConnection({required PeripheralSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelConnection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<ConnectionState> connectionState({required PeripheralSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ConnectionState;
  }

  /// Discovers services offered by the peripheral.
  Future<void> discoverServices({required PeripheralSession session, List<String>? serviceUuids}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<Service>> services({required PeripheralSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.services$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Service>();
  }

  /// Discovers characteristics offered by the service.
  Future<void> discoverCharacteristics({required PeripheralSession session, required String serviceUuid, List<String>? characteristicUuids, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverCharacteristics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid, characteristicUuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<Characteristic>> characteristics({required PeripheralSession session, required String serviceUuid}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.characteristics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Characteristic>();
  }

  /// Reads the value of the characteristic.
  Future<Uint8List> readCharacteristic({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid, characteristicUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Writes the value of the characteristic.
  Future<void> writeCharacteristic({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, required Uint8List value, bool withoutResponse = false, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid, characteristicUuid, value, withoutResponse]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> observeCharacteristic({bool observe = true, required PeripheralSession session, required String serviceUuid, required String characteristicUuid, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.observeCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[observe, session, serviceUuid, characteristicUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Reads the value of the descriptor.
  Future<Uint8List> readDescriptor({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, required String descriptorUuid, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid, characteristicUuid, descriptorUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Writes the value of the descriptor.
  Future<void> writeDescriptor({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, required String descriptorUuid, required Uint8List value, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid, characteristicUuid, descriptorUuid, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Requests a read of the RSSI for the peripheral.
  Future<int> readRssi({required PeripheralSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readRssi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Requests a MTU size change.
  Future<int> requestMtu({required PeripheralSession session, required int mtu}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.requestMtu$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, mtu]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// "Peripheral" APIs.
  Future<ClientState> peripheralManagerState({required PeripheralManagerSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripheralManagerState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ClientState;
  }

  Future<void> startAdvertising({required PeripheralManagerSession session, String? localName, List<String>? serviceUuids, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.startAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, localName, serviceUuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopAdvertising({required PeripheralManagerSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.stopAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> addService({required PeripheralManagerSession session, required MutableService service}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.addService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, service]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> removeService({required PeripheralManagerSession session, required String serviceUuid}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.removeService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> removeAllServices({required PeripheralManagerSession session}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.removeAllServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> respondToRequest({required PeripheralManagerSession session, required int requestId, required AttResult requestResult, Uint8List? value, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.respondToRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, requestId, requestResult, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> updateValue({required PeripheralManagerSession session, required String serviceUuid, required String characteristicUuid, required Uint8List value, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.updateValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session, serviceUuid, characteristicUuid, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

/// The APIs that are used from the host platform to communicate with the
/// flutter plugin.
abstract class ButaneFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// "Central Client" APIs.
  void onClientState(String? clientIdentifier, ClientState state);

  void onScanResult(ScanResult scanResult);

  /// "Peripheral" APIs.
  void onConnectionState(Peripheral peripheral, ConnectionState state);

  void onCharacteristicValue(Peripheral peripheral, Characteristic characteristic, Uint8List value);

  void onDescriptorValue(Peripheral peripheral, Descriptor descriptor, Uint8List value);

  /// "Peripheral Manager" APIs.
  void onPeripheralManagerState(String? clientIdentifier, ClientState state);

  void onServiceAdded(String serviceUuid, String? error);

  void onReadRequest(AttRequest request);

  void onWriteRequests(List<AttRequest> requests);

  void onCentralSubscribed(String? clientIdentifier, String centralIdentifier, String serviceUuid, String characteristicUuid);

  void onCentralUnsubscribed(String? clientIdentifier, String centralIdentifier, String serviceUuid, String characteristicUuid);

  void onReadyToUpdateSubscribers(String? clientIdentifier);

  static void setUp(ButaneFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_clientIdentifier = args[0] as String?;
          final ClientState arg_state = args[1]! as ClientState;
          try {
            api.onClientState(arg_clientIdentifier, arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ScanResult arg_scanResult = args[0]! as ScanResult;
          try {
            api.onScanResult(arg_scanResult);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Peripheral arg_peripheral = args[0]! as Peripheral;
          final ConnectionState arg_state = args[1]! as ConnectionState;
          try {
            api.onConnectionState(arg_peripheral, arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Peripheral arg_peripheral = args[0]! as Peripheral;
          final Characteristic arg_characteristic = args[1]! as Characteristic;
          final Uint8List arg_value = args[2]! as Uint8List;
          try {
            api.onCharacteristicValue(arg_peripheral, arg_characteristic, arg_value);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Peripheral arg_peripheral = args[0]! as Peripheral;
          final Descriptor arg_descriptor = args[1]! as Descriptor;
          final Uint8List arg_value = args[2]! as Uint8List;
          try {
            api.onDescriptorValue(arg_peripheral, arg_descriptor, arg_value);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onPeripheralManagerState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_clientIdentifier = args[0] as String?;
          final ClientState arg_state = args[1]! as ClientState;
          try {
            api.onPeripheralManagerState(arg_clientIdentifier, arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onServiceAdded$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_serviceUuid = args[0]! as String;
          final String? arg_error = args[1] as String?;
          try {
            api.onServiceAdded(arg_serviceUuid, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AttRequest arg_request = args[0]! as AttRequest;
          try {
            api.onReadRequest(arg_request);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onWriteRequests$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<AttRequest> arg_requests = (args[0]! as List<Object?>).cast<AttRequest>();
          try {
            api.onWriteRequests(arg_requests);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCentralSubscribed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_clientIdentifier = args[0] as String?;
          final String arg_centralIdentifier = args[1]! as String;
          final String arg_serviceUuid = args[2]! as String;
          final String arg_characteristicUuid = args[3]! as String;
          try {
            api.onCentralSubscribed(arg_clientIdentifier, arg_centralIdentifier, arg_serviceUuid, arg_characteristicUuid);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCentralUnsubscribed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_clientIdentifier = args[0] as String?;
          final String arg_centralIdentifier = args[1]! as String;
          final String arg_serviceUuid = args[2]! as String;
          final String arg_characteristicUuid = args[3]! as String;
          try {
            api.onCentralUnsubscribed(arg_clientIdentifier, arg_centralIdentifier, arg_serviceUuid, arg_characteristicUuid);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onReadyToUpdateSubscribers$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_clientIdentifier = args[0] as String?;
          try {
            api.onReadyToUpdateSubscribers(arg_clientIdentifier);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
