// Autogenerated from Pigeon (v15.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum ClientState {
  unknown,
  resetting,
  unsupported,
  unauthorized,
  poweredOff,
  poweredOn,
}

enum ConnectionState {
  disconnected,
  connecting,
  reconnecting,
  connected,
  disconnecting,
}

/// A unique identifier for a peripheral coupled with the [adapterIdentifier] and
/// [clientIdentifier] that discovered it.
///
/// The [clientIdentifier] is the identifier of the client that discovered the
/// peripheral. This is useful when multiple clients are connected to the same
/// adapter. If omitted, the default client is used.
///
/// The [adapterIdentifier] is the identifier of the adapter that discovered the
/// peripheral. This is useful when multiple adapters are available on the same
/// device. If omitted, the default adapter is used.
class Session {
  Session({
    this.peripheralIdentifier,
    this.clientIdentifier,
    this.adapterIdentifier,
    this.restorationIdentifier,
  });

  String? peripheralIdentifier;

  String? clientIdentifier;

  String? adapterIdentifier;

  String? restorationIdentifier;

  Object encode() {
    return <Object?>[
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ];
  }

  static Session decode(Object result) {
    result as List<Object?>;
    return Session(
      peripheralIdentifier: result[0] as String?,
      clientIdentifier: result[1] as String?,
      adapterIdentifier: result[2] as String?,
      restorationIdentifier: result[3] as String?,
    );
  }
}

class PeripheralSession {
  PeripheralSession({
    required this.peripheralIdentifier,
    this.clientIdentifier,
    this.adapterIdentifier,
    this.restorationIdentifier,
  });

  String peripheralIdentifier;

  String? clientIdentifier;

  String? adapterIdentifier;

  String? restorationIdentifier;

  Object encode() {
    return <Object?>[
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ];
  }

  static PeripheralSession decode(Object result) {
    result as List<Object?>;
    return PeripheralSession(
      peripheralIdentifier: result[0]! as String,
      clientIdentifier: result[1] as String?,
      adapterIdentifier: result[2] as String?,
      restorationIdentifier: result[3] as String?,
    );
  }
}

class Peripheral {
  Peripheral({
    required this.session,
    this.name,
    this.rssi,
    required this.state,
  });

  PeripheralSession session;

  String? name;

  int? rssi;

  ConnectionState state;

  Object encode() {
    return <Object?>[
      session.encode(),
      name,
      rssi,
      state.index,
    ];
  }

  static Peripheral decode(Object result) {
    result as List<Object?>;
    return Peripheral(
      session: PeripheralSession.decode(result[0]! as List<Object?>),
      name: result[1] as String?,
      rssi: result[2] as int?,
      state: ConnectionState.values[result[3]! as int],
    );
  }
}

class AdvertisementData {
  AdvertisementData({
    this.localName,
    this.manufacturerData,
    this.serviceUuids,
    this.serviceData,
    this.txPowerLevel,
    this.isConnectable,
  });

  String? localName;

  Uint8List? manufacturerData;

  List<String?>? serviceUuids;

  Map<String?, Uint8List?>? serviceData;

  int? txPowerLevel;

  bool? isConnectable;

  Object encode() {
    return <Object?>[
      localName,
      manufacturerData,
      serviceUuids,
      serviceData,
      txPowerLevel,
      isConnectable,
    ];
  }

  static AdvertisementData decode(Object result) {
    result as List<Object?>;
    return AdvertisementData(
      localName: result[0] as String?,
      manufacturerData: result[1] as Uint8List?,
      serviceUuids: (result[2] as List<Object?>?)?.cast<String?>(),
      serviceData: (result[3] as Map<Object?, Object?>?)?.cast<String?, Uint8List?>(),
      txPowerLevel: result[4] as int?,
      isConnectable: result[5] as bool?,
    );
  }
}

class ScanResult {
  ScanResult({
    required this.peripheral,
    required this.advertisementData,
  });

  Peripheral peripheral;

  AdvertisementData advertisementData;

  Object encode() {
    return <Object?>[
      peripheral.encode(),
      advertisementData.encode(),
    ];
  }

  static ScanResult decode(Object result) {
    result as List<Object?>;
    return ScanResult(
      peripheral: Peripheral.decode(result[0]! as List<Object?>),
      advertisementData: AdvertisementData.decode(result[1]! as List<Object?>),
    );
  }
}

class Service {
  Service({
    required this.uuid,
    this.isPrimary = false,
  });

  String uuid;

  bool isPrimary;

  Object encode() {
    return <Object?>[
      uuid,
      isPrimary,
    ];
  }

  static Service decode(Object result) {
    result as List<Object?>;
    return Service(
      uuid: result[0]! as String,
      isPrimary: result[1]! as bool,
    );
  }
}

class Characteristic {
  Characteristic({
    required this.uuid,
    this.value,
    this.descriptors,
    this.properties,
  });

  String uuid;

  Uint8List? value;

  List<Descriptor?>? descriptors;

  CharacteristicProperty? properties;

  Object encode() {
    return <Object?>[
      uuid,
      value,
      descriptors,
      properties?.encode(),
    ];
  }

  static Characteristic decode(Object result) {
    result as List<Object?>;
    return Characteristic(
      uuid: result[0]! as String,
      value: result[1] as Uint8List?,
      descriptors: (result[2] as List<Object?>?)?.cast<Descriptor?>(),
      properties: result[3] != null
          ? CharacteristicProperty.decode(result[3]! as List<Object?>)
          : null,
    );
  }
}

class Descriptor {
  Descriptor({
    required this.uuid,
    this.value,
  });

  String uuid;

  Uint8List? value;

  Object encode() {
    return <Object?>[
      uuid,
      value,
    ];
  }

  static Descriptor decode(Object result) {
    result as List<Object?>;
    return Descriptor(
      uuid: result[0]! as String,
      value: result[1] as Uint8List?,
    );
  }
}

class CharacteristicProperty {
  CharacteristicProperty({
    this.broadcast = false,
    this.read = false,
    this.writeWithoutResponse = false,
    this.write = false,
    this.notify = false,
    this.indicate = false,
    this.authenticatedSignedWrites = false,
    this.extendedProperties = false,
    this.notifyEncryptionRequired = false,
    this.indicateEncryptionRequired = false,
  });

  bool broadcast;

  bool read;

  bool writeWithoutResponse;

  bool write;

  bool notify;

  bool indicate;

  bool authenticatedSignedWrites;

  bool extendedProperties;

  bool notifyEncryptionRequired;

  bool indicateEncryptionRequired;

  Object encode() {
    return <Object?>[
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ];
  }

  static CharacteristicProperty decode(Object result) {
    result as List<Object?>;
    return CharacteristicProperty(
      broadcast: result[0]! as bool,
      read: result[1]! as bool,
      writeWithoutResponse: result[2]! as bool,
      write: result[3]! as bool,
      notify: result[4]! as bool,
      indicate: result[5]! as bool,
      authenticatedSignedWrites: result[6]! as bool,
      extendedProperties: result[7]! as bool,
      notifyEncryptionRequired: result[8]! as bool,
      indicateEncryptionRequired: result[9]! as bool,
    );
  }
}

class _ButaneHostApiCodec extends StandardMessageCodec {
  const _ButaneHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Characteristic) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is CharacteristicProperty) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is Descriptor) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is Peripheral) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PeripheralSession) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is Service) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is Session) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return Characteristic.decode(readValue(buffer)!);
      case 129: 
        return CharacteristicProperty.decode(readValue(buffer)!);
      case 130: 
        return Descriptor.decode(readValue(buffer)!);
      case 131: 
        return Peripheral.decode(readValue(buffer)!);
      case 132: 
        return PeripheralSession.decode(readValue(buffer)!);
      case 133: 
        return Service.decode(readValue(buffer)!);
      case 134: 
        return Session.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The APIs that are used to communicate from the flutter plugin to the
/// host platform.
class ButaneHostApi {
  /// Constructor for [ButaneHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ButaneHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _ButaneHostApiCodec();

  /// "Central" APIs.
  Future<ClientState> state({Session? session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.state';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return ClientState.values[__pigeon_replyList[0]! as int];
    }
  }

  /// Scans for peripherals that are advertising services.
  Future<void> scan({Session? session, List<String?>? forServices = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.scan';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, forServices]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelScan({Session? session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelScan';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// A list of known peripherals optionally filtered by their identifiers.
  Future<List<Peripheral?>> peripherals({Session? session, List<String?> peripheralIdentifiers = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripherals';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, peripheralIdentifiers]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<Peripheral?>();
    }
  }

  /// A list of connected peripherals identified by an offered service.
  Future<List<Peripheral?>> connectedPeripherals({Session? session, List<String?> serviceUuids = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectedPeripherals';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuids]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<Peripheral?>();
    }
  }

  /// Establishes a connection to the peripheral.
  Future<void> connect({required PeripheralSession session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connect';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Cancels an active or pending connection to the peripheral.
  Future<void> cancelConnection({required PeripheralSession session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelConnection';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<ConnectionState> connectionState({required PeripheralSession session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectionState';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return ConnectionState.values[__pigeon_replyList[0]! as int];
    }
  }

  /// Discovers services offered by the peripheral.
  Future<void> discoverServices({required PeripheralSession session, List<String?>? serviceUuids = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverServices';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuids]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<Service?>> services({required PeripheralSession session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.services';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<Service?>();
    }
  }

  /// Discovers characteristics offered by the service.
  Future<void> discoverCharacteristics({required PeripheralSession session, required String serviceUuid, List<String?>? characteristicUuids = const [],}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverCharacteristics';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuid, characteristicUuids]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<Characteristic?>> characteristics({required PeripheralSession session, required String serviceUuid}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.characteristics';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuid]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<Characteristic?>();
    }
  }

  /// Reads the value of the characteristic.
  Future<Uint8List> readCharacteristic({required PeripheralSession session, required String serviceUuid, required String characteristicUuid,}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readCharacteristic';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuid, characteristicUuid]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Uint8List?)!;
    }
  }

  /// Writes the value of the characteristic.
  Future<void> writeCharacteristic({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, required Uint8List value, bool withoutResponse = false,}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeCharacteristic';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuid, characteristicUuid, value, withoutResponse]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> observeCharacteristic({bool observe = true, required PeripheralSession session, required String serviceUuid, required String characteristicUuid,}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.observeCharacteristic';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[observe, session, serviceUuid, characteristicUuid]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Reads the value of the descriptor.
  Future<Uint8List> readDescriptor({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, required String descriptorUuid,}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readDescriptor';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuid, characteristicUuid, descriptorUuid]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Uint8List?)!;
    }
  }

  /// Writes the value of the descriptor.
  Future<void> writeDescriptor({required PeripheralSession session, required String serviceUuid, required String characteristicUuid, required String descriptorUuid, required Uint8List value,}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeDescriptor';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, serviceUuid, characteristicUuid, descriptorUuid, value]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Requests a read of the RSSI for the peripheral.
  Future<int> readRssi({required PeripheralSession session}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readRssi';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Requests a MTU size change.
  Future<int> requestMtu({required PeripheralSession session, required int mtu}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.requestMtu';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[session, mtu]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }
}

class _ButaneFlutterApiCodec extends StandardMessageCodec {
  const _ButaneFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is AdvertisementData) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is Characteristic) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CharacteristicProperty) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is Descriptor) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is Peripheral) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PeripheralSession) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ScanResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return AdvertisementData.decode(readValue(buffer)!);
      case 129: 
        return Characteristic.decode(readValue(buffer)!);
      case 130: 
        return CharacteristicProperty.decode(readValue(buffer)!);
      case 131: 
        return Descriptor.decode(readValue(buffer)!);
      case 132: 
        return Peripheral.decode(readValue(buffer)!);
      case 133: 
        return PeripheralSession.decode(readValue(buffer)!);
      case 134: 
        return ScanResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The APIs that are used from the host platform to communicate with the
/// flutter plugin.
abstract class ButaneFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _ButaneFlutterApiCodec();

  /// "Central Client" APIs.
  void onClientState(String? clientIdentifier, ClientState state);

  void onScanResult(ScanResult scanResult);

  /// "Peripheral" APIs.
  void onConnectionState(Peripheral peripheral, ConnectionState state);

  void onCharacteristicValue(Peripheral peripheral, Characteristic characteristic, Uint8List value);

  void onDescriptorValue(Peripheral peripheral, Descriptor descriptor, Uint8List value);

  static void setup(ButaneFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_clientIdentifier = (args[0] as String?);
          final ClientState? arg_state = args[1] == null ? null : ClientState.values[args[1]! as int];
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState was null, expected non-null ClientState.');
          try {
            api.onClientState(arg_clientIdentifier, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ScanResult? arg_scanResult = (args[0] as ScanResult?);
          assert(arg_scanResult != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult was null, expected non-null ScanResult.');
          try {
            api.onScanResult(arg_scanResult!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Peripheral? arg_peripheral = (args[0] as Peripheral?);
          assert(arg_peripheral != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState was null, expected non-null Peripheral.');
          final ConnectionState? arg_state = args[1] == null ? null : ConnectionState.values[args[1]! as int];
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState was null, expected non-null ConnectionState.');
          try {
            api.onConnectionState(arg_peripheral!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Peripheral? arg_peripheral = (args[0] as Peripheral?);
          assert(arg_peripheral != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue was null, expected non-null Peripheral.');
          final Characteristic? arg_characteristic = (args[1] as Characteristic?);
          assert(arg_characteristic != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue was null, expected non-null Characteristic.');
          final Uint8List? arg_value = (args[2] as Uint8List?);
          assert(arg_value != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue was null, expected non-null Uint8List.');
          try {
            api.onCharacteristicValue(arg_peripheral!, arg_characteristic!, arg_value!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Peripheral? arg_peripheral = (args[0] as Peripheral?);
          assert(arg_peripheral != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue was null, expected non-null Peripheral.');
          final Descriptor? arg_descriptor = (args[1] as Descriptor?);
          assert(arg_descriptor != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue was null, expected non-null Descriptor.');
          final Uint8List? arg_value = (args[2] as Uint8List?);
          assert(arg_value != null,
              'Argument for dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue was null, expected non-null Uint8List.');
          try {
            api.onDescriptorValue(arg_peripheral!, arg_descriptor!, arg_value!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
