name: butane_core_bluetooth_example
description: "Demonstrates how to use the butane_core_bluetooth plugin."
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  butane_core_bluetooth:
    path: ../
  butane_platform_interface:
    path: ../../butane_platform_interface

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
