name: butane_bluez
description: Linux implementation of the butane BLE plugin using BlueZ.
version: 0.1.0
repository: https://github.com/nicholasspencer/butane_flutter
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  butane_dart_bluez: ^0.1.0
  butane_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  plugin:
    implements: butane_platform_interface
    platforms:
      linux:
        dartPluginClass: ButaneBluez
