name: butane_bluez
description: Linux implementation of the butane BLE plugin using BlueZ.
version: 0.0.1
repository: https://github.com/nicholasspencer/butane_flutter
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  butane_dart_bluez:
    path: ../butane_dart_bluez
  butane_platform_interface:
    path: ../butane_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  plugin:
    implements: butane_platform_interface
    platforms:
      linux:
        dartPluginClass: ButaneBluez
