name: butane_workspace
description: ":fire:"
version: 0.0.1
homepage: https://github.com/nicholasspencer/butane
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/butane
  - packages/butane_platform_interface
  - packages/butane_core_bluetooth
  - packages/butane_bluez
  - packages/butane_android
  - packages/butane_harness
  - packages/butane/example
  - packages/butane_core_bluetooth/example
  - packages/butane_android/example
  - packages/butane_coordinator
