// Autogenerated from Pigeon (v15.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum ClientState: Int {
  case unknown = 0
  case resetting = 1
  case unsupported = 2
  case unauthorized = 3
  case poweredOff = 4
  case poweredOn = 5
}

enum ConnectionState: Int {
  case disconnected = 0
  case connecting = 1
  case reconnecting = 2
  case connected = 3
  case disconnecting = 4
}

/// A unique identifier for a peripheral coupled with the [adapterIdentifier] and
/// [clientIdentifier] that discovered it.
///
/// The [clientIdentifier] is the identifier of the client that discovered the
/// peripheral. This is useful when multiple clients are connected to the same
/// adapter. If omitted, the default client is used.
///
/// The [adapterIdentifier] is the identifier of the adapter that discovered the
/// peripheral. This is useful when multiple adapters are available on the same
/// device. If omitted, the default adapter is used.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PeripheralSessionIdentifier {
  var identifier: String
  var clientIdentifier: String? = nil
  var adapterIdentifier: String? = nil

  static func fromList(_ list: [Any?]) -> PeripheralSessionIdentifier? {
    let identifier = list[0] as! String
    let clientIdentifier: String? = nilOrValue(list[1])
    let adapterIdentifier: String? = nilOrValue(list[2])

    return PeripheralSessionIdentifier(
      identifier: identifier,
      clientIdentifier: clientIdentifier,
      adapterIdentifier: adapterIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      clientIdentifier,
      adapterIdentifier,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PeripheralData {
  var identifier: PeripheralSessionIdentifier
  var name: String? = nil
  var rssi: Double? = nil
  var state: ConnectionState

  static func fromList(_ list: [Any?]) -> PeripheralData? {
    let identifier = PeripheralSessionIdentifier.fromList(list[0] as! [Any?])!
    let name: String? = nilOrValue(list[1])
    let rssi: Double? = nilOrValue(list[2])
    let state = ConnectionState(rawValue: list[3] as! Int)!

    return PeripheralData(
      identifier: identifier,
      name: name,
      rssi: rssi,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      identifier.toList(),
      name,
      rssi,
      state.rawValue,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AdvertisementData {
  var localName: String? = nil
  var txPowerLevel: Int64? = nil
  var manufacturerData: FlutterStandardTypedData? = nil
  var serviceData: [String?: FlutterStandardTypedData?]? = nil
  var serviceUuids: [String?]? = nil
  var isConnectable: Bool

  static func fromList(_ list: [Any?]) -> AdvertisementData? {
    let localName: String? = nilOrValue(list[0])
    let txPowerLevel: Int64? = isNullish(list[1]) ? nil : (list[1] is Int64? ? list[1] as! Int64? : Int64(list[1] as! Int32))
    let manufacturerData: FlutterStandardTypedData? = nilOrValue(list[2])
    let serviceData: [String?: FlutterStandardTypedData?]? = nilOrValue(list[3])
    let serviceUuids: [String?]? = nilOrValue(list[4])
    let isConnectable = list[5] as! Bool

    return AdvertisementData(
      localName: localName,
      txPowerLevel: txPowerLevel,
      manufacturerData: manufacturerData,
      serviceData: serviceData,
      serviceUuids: serviceUuids,
      isConnectable: isConnectable
    )
  }
  func toList() -> [Any?] {
    return [
      localName,
      txPowerLevel,
      manufacturerData,
      serviceData,
      serviceUuids,
      isConnectable,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanData {
  var peripheral: PeripheralData
  var advertisementData: AdvertisementData

  static func fromList(_ list: [Any?]) -> ScanData? {
    let peripheral = PeripheralData.fromList(list[0] as! [Any?])!
    let advertisementData = AdvertisementData.fromList(list[1] as! [Any?])!

    return ScanData(
      peripheral: peripheral,
      advertisementData: advertisementData
    )
  }
  func toList() -> [Any?] {
    return [
      peripheral.toList(),
      advertisementData.toList(),
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ServiceData {
  var uuid: String
  var isPrimary: Bool? = nil

  static func fromList(_ list: [Any?]) -> ServiceData? {
    let uuid = list[0] as! String
    let isPrimary: Bool? = nilOrValue(list[1])

    return ServiceData(
      uuid: uuid,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      isPrimary,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CharacteristicData {
  var uuid: String
  /// List of bytes
  var value: [Int64?]? = nil
  var descriptors: [DescriptorData?]? = nil
  var properties: CharacteristicProperty? = nil

  static func fromList(_ list: [Any?]) -> CharacteristicData? {
    let uuid = list[0] as! String
    let value: [Int64?]? = nilOrValue(list[1])
    let descriptors: [DescriptorData?]? = nilOrValue(list[2])
    var properties: CharacteristicProperty? = nil
    if let propertiesList: [Any?] = nilOrValue(list[3]) {
      properties = CharacteristicProperty.fromList(propertiesList)
    }

    return CharacteristicData(
      uuid: uuid,
      value: value,
      descriptors: descriptors,
      properties: properties
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      value,
      descriptors,
      properties?.toList(),
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DescriptorData {
  var uuid: String
  /// List of bytes
  var value: [Int64?]? = nil

  static func fromList(_ list: [Any?]) -> DescriptorData? {
    let uuid = list[0] as! String
    let value: [Int64?]? = nilOrValue(list[1])

    return DescriptorData(
      uuid: uuid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      value,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CharacteristicProperty {
  var broadcast: Bool
  var read: Bool
  var writeWithoutResponse: Bool
  var write: Bool
  var notify: Bool
  var indicate: Bool
  var authenticatedSignedWrites: Bool
  var extendedProperties: Bool
  var notifyEncryptionRequired: Bool
  var indicateEncryptionRequired: Bool

  static func fromList(_ list: [Any?]) -> CharacteristicProperty? {
    let broadcast = list[0] as! Bool
    let read = list[1] as! Bool
    let writeWithoutResponse = list[2] as! Bool
    let write = list[3] as! Bool
    let notify = list[4] as! Bool
    let indicate = list[5] as! Bool
    let authenticatedSignedWrites = list[6] as! Bool
    let extendedProperties = list[7] as! Bool
    let notifyEncryptionRequired = list[8] as! Bool
    let indicateEncryptionRequired = list[9] as! Bool

    return CharacteristicProperty(
      broadcast: broadcast,
      read: read,
      writeWithoutResponse: writeWithoutResponse,
      write: write,
      notify: notify,
      indicate: indicate,
      authenticatedSignedWrites: authenticatedSignedWrites,
      extendedProperties: extendedProperties,
      notifyEncryptionRequired: notifyEncryptionRequired,
      indicateEncryptionRequired: indicateEncryptionRequired
    )
  }
  func toList() -> [Any?] {
    return [
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ]
  }
}

private class ButaneHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return CharacteristicData.fromList(self.readValue() as! [Any?])
      case 129:
        return CharacteristicProperty.fromList(self.readValue() as! [Any?])
      case 130:
        return DescriptorData.fromList(self.readValue() as! [Any?])
      case 131:
        return PeripheralData.fromList(self.readValue() as! [Any?])
      case 132:
        return PeripheralSessionIdentifier.fromList(self.readValue() as! [Any?])
      case 133:
        return ServiceData.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class ButaneHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CharacteristicData {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicProperty {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DescriptorData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PeripheralData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PeripheralSessionIdentifier {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ServiceData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ButaneHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ButaneHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ButaneHostApiCodecWriter(data: data)
  }
}

class ButaneHostApiCodec: FlutterStandardMessageCodec {
  static let shared = ButaneHostApiCodec(readerWriter: ButaneHostApiCodecReaderWriter())
}

/// The APIs that are used to communicate from the flutter plugin to the
/// host platform.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ButaneHostApi {
  /// "Central" APIs.
  func state(clientIdentifier: String?, completion: @escaping (Result<ClientState, Error>) -> Void)
  /// Scans for peripherals that are advertising services.
  func scan(clientIdentifier: String?, forServices: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelScan(clientIdentifier: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// A list of known peripherals optionally filtered by their identifiers.
  func peripherals(clientIdentifier: String?, peripheralIdentifiers: [String]?, completion: @escaping (Result<[PeripheralData], Error>) -> Void)
  /// A list of connected peripherals identified by an offered service.
  func connectedPeripherals(clientIdentifier: String?, serviceUuids: [String]?, completion: @escaping (Result<[PeripheralData], Error>) -> Void)
  /// Establishes a connection to the peripheral.
  func connect(sessionIdentifier: PeripheralSessionIdentifier, completion: @escaping (Result<Void, Error>) -> Void)
  /// Cancels an active or pending connection to the peripheral.
  func cancelConnection(sessionIdentifier: PeripheralSessionIdentifier, completion: @escaping (Result<Void, Error>) -> Void)
  func connectionState(sessionIdentifier: PeripheralSessionIdentifier, completion: @escaping (Result<ConnectionState, Error>) -> Void)
  /// Discovers services offered by the peripheral.
  func discoverServices(sessionIdentifier: PeripheralSessionIdentifier, serviceUuids: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func services(sessionIdentifier: PeripheralSessionIdentifier, completion: @escaping (Result<[ServiceData], Error>) -> Void)
  /// Discovers characteristics offered by the service.
  func discoverCharacteristics(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, characteristicUuids: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func characteristics(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, completion: @escaping (Result<[CharacteristicData], Error>) -> Void)
  /// Reads the value of the characteristic.
  func readCharacteristic(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Writes the value of the characteristic.
  func writeCharacteristic(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, characteristicUuid: String, value: [Int64], withoutResponse: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func watchCharacteristic(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Enables notifications or indications for the characteristic.
  func setNotification(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, characteristicUuid: String, enabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Reads the value of the descriptor.
  func readDescriptor(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, descriptorUuid: String, completion: @escaping (Result<[Int64], Error>) -> Void)
  /// Writes the value of the descriptor.
  func writeDescriptor(sessionIdentifier: PeripheralSessionIdentifier, serviceUuid: String, descriptorUuid: String, value: [Int64], completion: @escaping (Result<Void, Error>) -> Void)
  /// Requests a read of the RSSI for the peripheral.
  func readRssi(sessionIdentifier: PeripheralSessionIdentifier, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Requests a MTU size change.
  func requestMtu(sessionIdentifier: PeripheralSessionIdentifier, mtu: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ButaneHostApiSetup {
  /// The codec used by ButaneHostApi.
  static var codec: FlutterStandardMessageCodec { ButaneHostApiCodec.shared }
  /// Sets up an instance of `ButaneHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ButaneHostApi?) {
    /// "Central" APIs.
    let stateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.state", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdentifierArg: String? = nilOrValue(args[0])
        api.state(clientIdentifier: clientIdentifierArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res.rawValue))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      stateChannel.setMessageHandler(nil)
    }
    /// Scans for peripherals that are advertising services.
    let scanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.scan", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdentifierArg: String? = nilOrValue(args[0])
        let forServicesArg: [String]? = nilOrValue(args[1])
        api.scan(clientIdentifier: clientIdentifierArg, forServices: forServicesArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      scanChannel.setMessageHandler(nil)
    }
    let cancelScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelScan", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdentifierArg: String? = nilOrValue(args[0])
        api.cancelScan(clientIdentifier: clientIdentifierArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      cancelScanChannel.setMessageHandler(nil)
    }
    /// A list of known peripherals optionally filtered by their identifiers.
    let peripheralsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripherals", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      peripheralsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdentifierArg: String? = nilOrValue(args[0])
        let peripheralIdentifiersArg: [String]? = nilOrValue(args[1])
        api.peripherals(clientIdentifier: clientIdentifierArg, peripheralIdentifiers: peripheralIdentifiersArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      peripheralsChannel.setMessageHandler(nil)
    }
    /// A list of connected peripherals identified by an offered service.
    let connectedPeripheralsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectedPeripherals", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectedPeripheralsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdentifierArg: String? = nilOrValue(args[0])
        let serviceUuidsArg: [String]? = nilOrValue(args[1])
        api.connectedPeripherals(clientIdentifier: clientIdentifierArg, serviceUuids: serviceUuidsArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      connectedPeripheralsChannel.setMessageHandler(nil)
    }
    /// Establishes a connection to the peripheral.
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connect", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        api.connect(sessionIdentifier: sessionIdentifierArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    /// Cancels an active or pending connection to the peripheral.
    let cancelConnectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelConnection", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelConnectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        api.cancelConnection(sessionIdentifier: sessionIdentifierArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      cancelConnectionChannel.setMessageHandler(nil)
    }
    let connectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectionState", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        api.connectionState(sessionIdentifier: sessionIdentifierArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res.rawValue))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      connectionStateChannel.setMessageHandler(nil)
    }
    /// Discovers services offered by the peripheral.
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverServices", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidsArg: [String]? = nilOrValue(args[1])
        api.discoverServices(sessionIdentifier: sessionIdentifierArg, serviceUuids: serviceUuidsArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let servicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.services", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      servicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        api.services(sessionIdentifier: sessionIdentifierArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      servicesChannel.setMessageHandler(nil)
    }
    /// Discovers characteristics offered by the service.
    let discoverCharacteristicsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverCharacteristics", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverCharacteristicsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let characteristicUuidsArg: [String]? = nilOrValue(args[2])
        api.discoverCharacteristics(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, characteristicUuids: characteristicUuidsArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      discoverCharacteristicsChannel.setMessageHandler(nil)
    }
    let characteristicsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.characteristics", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      characteristicsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        api.characteristics(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      characteristicsChannel.setMessageHandler(nil)
    }
    /// Reads the value of the characteristic.
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readCharacteristic", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.readCharacteristic(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    /// Writes the value of the characteristic.
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeCharacteristic", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let valueArg = args[3] as! [Int64]
        let withoutResponseArg = args[4] as! Bool
        api.writeCharacteristic(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, value: valueArg, withoutResponse: withoutResponseArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    let watchCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.watchCharacteristic", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      watchCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.watchCharacteristic(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      watchCharacteristicChannel.setMessageHandler(nil)
    }
    /// Enables notifications or indications for the characteristic.
    let setNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.setNotification", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let enabledArg = args[3] as! Bool
        api.setNotification(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, enabled: enabledArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      setNotificationChannel.setMessageHandler(nil)
    }
    /// Reads the value of the descriptor.
    let readDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readDescriptor", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let descriptorUuidArg = args[2] as! String
        api.readDescriptor(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, descriptorUuid: descriptorUuidArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      readDescriptorChannel.setMessageHandler(nil)
    }
    /// Writes the value of the descriptor.
    let writeDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeDescriptor", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let serviceUuidArg = args[1] as! String
        let descriptorUuidArg = args[2] as! String
        let valueArg = args[3] as! [Int64]
        api.writeDescriptor(sessionIdentifier: sessionIdentifierArg, serviceUuid: serviceUuidArg, descriptorUuid: descriptorUuidArg, value: valueArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      writeDescriptorChannel.setMessageHandler(nil)
    }
    /// Requests a read of the RSSI for the peripheral.
    let readRssiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readRssi", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRssiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        api.readRssi(sessionIdentifier: sessionIdentifierArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      readRssiChannel.setMessageHandler(nil)
    }
    /// Requests a MTU size change.
    let requestMtuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.requestMtu", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMtuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdentifierArg = args[0] as! PeripheralSessionIdentifier
        let mtuArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        api.requestMtu(sessionIdentifier: sessionIdentifierArg, mtu: mtuArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      requestMtuChannel.setMessageHandler(nil)
    }
  }
}
private class ButaneFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return AdvertisementData.fromList(self.readValue() as! [Any?])
      case 129:
        return CharacteristicData.fromList(self.readValue() as! [Any?])
      case 130:
        return CharacteristicProperty.fromList(self.readValue() as! [Any?])
      case 131:
        return DescriptorData.fromList(self.readValue() as! [Any?])
      case 132:
        return PeripheralData.fromList(self.readValue() as! [Any?])
      case 133:
        return PeripheralSessionIdentifier.fromList(self.readValue() as! [Any?])
      case 134:
        return ScanData.fromList(self.readValue() as! [Any?])
      case 135:
        return ServiceData.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class ButaneFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AdvertisementData {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicProperty {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DescriptorData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PeripheralData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PeripheralSessionIdentifier {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ScanData {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ServiceData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ButaneFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ButaneFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ButaneFlutterApiCodecWriter(data: data)
  }
}

class ButaneFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = ButaneFlutterApiCodec(readerWriter: ButaneFlutterApiCodecReaderWriter())
}

/// The APIs that are used from the host platform to communicate with the
/// flutter plugin.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ButaneFlutterApiProtocol {
  /// "Central Client" APIs.
  func onClientState(clientIdentifier clientIdentifierArg: String?, state stateArg: ClientState, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onScanResult(scanResult scanResultArg: ScanData, completion: @escaping (Result<Void, FlutterError>) -> Void)
  /// "Peripheral" APIs.
  func onConnectionState(peripheral peripheralArg: PeripheralData, state stateArg: ConnectionState, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onServicesDiscovered(peripheral peripheralArg: PeripheralData, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onCharacteristicsDiscovered(peripheral peripheralArg: PeripheralData, service serviceArg: ServiceData, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onDescriptorsDiscovered(peripheral peripheralArg: PeripheralData, characteristic characteristicArg: CharacteristicData, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onCharacteristicValue(peripheral peripheralArg: PeripheralData, characteristic characteristicArg: CharacteristicData, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onDescriptorValue(peripheral peripheralArg: PeripheralData, descriptor descriptorArg: DescriptorData, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onRssi(peripheral peripheralArg: PeripheralData, rssi rssiArg: Int64, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class ButaneFlutterApi: ButaneFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return ButaneFlutterApiCodec.shared
  }
  /// "Central Client" APIs.
  func onClientState(clientIdentifier clientIdentifierArg: String?, state stateArg: ClientState, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdentifierArg, stateArg.rawValue] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onScanResult(scanResult scanResultArg: ScanData, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([scanResultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// "Peripheral" APIs.
  func onConnectionState(peripheral peripheralArg: PeripheralData, state stateArg: ConnectionState, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, stateArg.rawValue] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onServicesDiscovered(peripheral peripheralArg: PeripheralData, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onServicesDiscovered"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onCharacteristicsDiscovered(peripheral peripheralArg: PeripheralData, service serviceArg: ServiceData, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicsDiscovered"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, serviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDescriptorsDiscovered(peripheral peripheralArg: PeripheralData, characteristic characteristicArg: CharacteristicData, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorsDiscovered"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, characteristicArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onCharacteristicValue(peripheral peripheralArg: PeripheralData, characteristic characteristicArg: CharacteristicData, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, characteristicArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDescriptorValue(peripheral peripheralArg: PeripheralData, descriptor descriptorArg: DescriptorData, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, descriptorArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRssi(peripheral peripheralArg: PeripheralData, rssi rssiArg: Int64, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onRssi"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, rssiArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
}
