// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsApi(lhsKey, rhsKey) {
          if deepEqualsApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum ClientState: Int {
  case unknown = 0
  case resetting = 1
  case unsupported = 2
  case unauthorized = 3
  case poweredOff = 4
  case poweredOn = 5
}

enum ConnectionState: Int {
  case disconnected = 0
  case connecting = 1
  case reconnecting = 2
  case connected = 3
  case disconnecting = 4
}

enum AttResult: Int {
  case success = 0
  case invalidHandle = 1
  case readNotPermitted = 2
  case writeNotPermitted = 3
  case invalidOffset = 4
  case attributeNotFound = 5
  case unlikelyError = 6
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol Session {

}

/// A unique identifier for a peripheral coupled with the [adapterIdentifier] and
/// [clientIdentifier] that discovered it.
///
/// The [clientIdentifier] is the identifier of the client that discovered the
/// peripheral. This is useful when multiple clients are connected to the same
/// adapter. If omitted, the default client is used.
///
/// The [adapterIdentifier] is the identifier of the adapter that discovered the
/// peripheral. This is useful when multiple adapters are available on the same
/// device. If omitted, the default adapter is used.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ClientSession: Session {
  var peripheralIdentifier: String? = nil
  var clientIdentifier: String? = nil
  var adapterIdentifier: String? = nil
  var restorationIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientSession? {
    let peripheralIdentifier: String? = nilOrValue(pigeonVar_list[0])
    let clientIdentifier: String? = nilOrValue(pigeonVar_list[1])
    let adapterIdentifier: String? = nilOrValue(pigeonVar_list[2])
    let restorationIdentifier: String? = nilOrValue(pigeonVar_list[3])

    return ClientSession(
      peripheralIdentifier: peripheralIdentifier,
      clientIdentifier: clientIdentifier,
      adapterIdentifier: adapterIdentifier,
      restorationIdentifier: restorationIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ]
  }
  static func == (lhs: ClientSession, rhs: ClientSession) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.peripheralIdentifier, rhs.peripheralIdentifier) && deepEqualsApi(lhs.clientIdentifier, rhs.clientIdentifier) && deepEqualsApi(lhs.adapterIdentifier, rhs.adapterIdentifier) && deepEqualsApi(lhs.restorationIdentifier, rhs.restorationIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientSession")
    deepHashApi(value: peripheralIdentifier, hasher: &hasher)
    deepHashApi(value: clientIdentifier, hasher: &hasher)
    deepHashApi(value: adapterIdentifier, hasher: &hasher)
    deepHashApi(value: restorationIdentifier, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PeripheralSession: Session {
  var peripheralIdentifier: String
  var clientIdentifier: String? = nil
  var adapterIdentifier: String? = nil
  var restorationIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeripheralSession? {
    let peripheralIdentifier = pigeonVar_list[0] as! String
    let clientIdentifier: String? = nilOrValue(pigeonVar_list[1])
    let adapterIdentifier: String? = nilOrValue(pigeonVar_list[2])
    let restorationIdentifier: String? = nilOrValue(pigeonVar_list[3])

    return PeripheralSession(
      peripheralIdentifier: peripheralIdentifier,
      clientIdentifier: clientIdentifier,
      adapterIdentifier: adapterIdentifier,
      restorationIdentifier: restorationIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ]
  }
  static func == (lhs: PeripheralSession, rhs: PeripheralSession) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.peripheralIdentifier, rhs.peripheralIdentifier) && deepEqualsApi(lhs.clientIdentifier, rhs.clientIdentifier) && deepEqualsApi(lhs.adapterIdentifier, rhs.adapterIdentifier) && deepEqualsApi(lhs.restorationIdentifier, rhs.restorationIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeripheralSession")
    deepHashApi(value: peripheralIdentifier, hasher: &hasher)
    deepHashApi(value: clientIdentifier, hasher: &hasher)
    deepHashApi(value: adapterIdentifier, hasher: &hasher)
    deepHashApi(value: restorationIdentifier, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PeripheralManagerSession: Session {
  var clientIdentifier: String? = nil
  var adapterIdentifier: String? = nil
  var restorationIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeripheralManagerSession? {
    let clientIdentifier: String? = nilOrValue(pigeonVar_list[0])
    let adapterIdentifier: String? = nilOrValue(pigeonVar_list[1])
    let restorationIdentifier: String? = nilOrValue(pigeonVar_list[2])

    return PeripheralManagerSession(
      clientIdentifier: clientIdentifier,
      adapterIdentifier: adapterIdentifier,
      restorationIdentifier: restorationIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    ]
  }
  static func == (lhs: PeripheralManagerSession, rhs: PeripheralManagerSession) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.clientIdentifier, rhs.clientIdentifier) && deepEqualsApi(lhs.adapterIdentifier, rhs.adapterIdentifier) && deepEqualsApi(lhs.restorationIdentifier, rhs.restorationIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeripheralManagerSession")
    deepHashApi(value: clientIdentifier, hasher: &hasher)
    deepHashApi(value: adapterIdentifier, hasher: &hasher)
    deepHashApi(value: restorationIdentifier, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Peripheral: Hashable {
  var session: PeripheralSession
  var name: String? = nil
  var rssi: Int64? = nil
  var state: ConnectionState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Peripheral? {
    let session = pigeonVar_list[0] as! PeripheralSession
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi: Int64? = nilOrValue(pigeonVar_list[2])
    let state = pigeonVar_list[3] as! ConnectionState

    return Peripheral(
      session: session,
      name: name,
      rssi: rssi,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      session,
      name,
      rssi,
      state,
    ]
  }
  static func == (lhs: Peripheral, rhs: Peripheral) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.session, rhs.session) && deepEqualsApi(lhs.name, rhs.name) && deepEqualsApi(lhs.rssi, rhs.rssi) && deepEqualsApi(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Peripheral")
    deepHashApi(value: session, hasher: &hasher)
    deepHashApi(value: name, hasher: &hasher)
    deepHashApi(value: rssi, hasher: &hasher)
    deepHashApi(value: state, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AdvertisementData: Hashable {
  var localName: String? = nil
  var manufacturerData: FlutterStandardTypedData? = nil
  var serviceUuids: [String?]? = nil
  var serviceData: [String?: FlutterStandardTypedData?]? = nil
  var txPowerLevel: Int64? = nil
  var isConnectable: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdvertisementData? {
    let localName: String? = nilOrValue(pigeonVar_list[0])
    let manufacturerData: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let serviceUuids: [String?]? = nilOrValue(pigeonVar_list[2])
    let serviceData: [String?: FlutterStandardTypedData?]? = nilOrValue(pigeonVar_list[3])
    let txPowerLevel: Int64? = nilOrValue(pigeonVar_list[4])
    let isConnectable: Bool? = nilOrValue(pigeonVar_list[5])

    return AdvertisementData(
      localName: localName,
      manufacturerData: manufacturerData,
      serviceUuids: serviceUuids,
      serviceData: serviceData,
      txPowerLevel: txPowerLevel,
      isConnectable: isConnectable
    )
  }
  func toList() -> [Any?] {
    return [
      localName,
      manufacturerData,
      serviceUuids,
      serviceData,
      txPowerLevel,
      isConnectable,
    ]
  }
  static func == (lhs: AdvertisementData, rhs: AdvertisementData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.localName, rhs.localName) && deepEqualsApi(lhs.manufacturerData, rhs.manufacturerData) && deepEqualsApi(lhs.serviceUuids, rhs.serviceUuids) && deepEqualsApi(lhs.serviceData, rhs.serviceData) && deepEqualsApi(lhs.txPowerLevel, rhs.txPowerLevel) && deepEqualsApi(lhs.isConnectable, rhs.isConnectable)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AdvertisementData")
    deepHashApi(value: localName, hasher: &hasher)
    deepHashApi(value: manufacturerData, hasher: &hasher)
    deepHashApi(value: serviceUuids, hasher: &hasher)
    deepHashApi(value: serviceData, hasher: &hasher)
    deepHashApi(value: txPowerLevel, hasher: &hasher)
    deepHashApi(value: isConnectable, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanResult: Hashable {
  var peripheral: Peripheral
  var advertisementData: AdvertisementData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanResult? {
    let peripheral = pigeonVar_list[0] as! Peripheral
    let advertisementData = pigeonVar_list[1] as! AdvertisementData

    return ScanResult(
      peripheral: peripheral,
      advertisementData: advertisementData
    )
  }
  func toList() -> [Any?] {
    return [
      peripheral,
      advertisementData,
    ]
  }
  static func == (lhs: ScanResult, rhs: ScanResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.peripheral, rhs.peripheral) && deepEqualsApi(lhs.advertisementData, rhs.advertisementData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanResult")
    deepHashApi(value: peripheral, hasher: &hasher)
    deepHashApi(value: advertisementData, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol AttributeData {

}

/// Generated class from Pigeon that represents data sent in messages.
struct Service: AttributeData {
  var uuid: String
  var isPrimary: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Service? {
    let uuid = pigeonVar_list[0] as! String
    let isPrimary = pigeonVar_list[1] as! Bool

    return Service(
      uuid: uuid,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      isPrimary,
    ]
  }
  static func == (lhs: Service, rhs: Service) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.uuid, rhs.uuid) && deepEqualsApi(lhs.isPrimary, rhs.isPrimary)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Service")
    deepHashApi(value: uuid, hasher: &hasher)
    deepHashApi(value: isPrimary, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Characteristic: AttributeData {
  var uuid: String
  var value: FlutterStandardTypedData? = nil
  var descriptors: [Descriptor?]? = nil
  var properties: CharacteristicProperty? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Characteristic? {
    let uuid = pigeonVar_list[0] as! String
    let value: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let descriptors: [Descriptor?]? = nilOrValue(pigeonVar_list[2])
    let properties: CharacteristicProperty? = nilOrValue(pigeonVar_list[3])

    return Characteristic(
      uuid: uuid,
      value: value,
      descriptors: descriptors,
      properties: properties
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      value,
      descriptors,
      properties,
    ]
  }
  static func == (lhs: Characteristic, rhs: Characteristic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.uuid, rhs.uuid) && deepEqualsApi(lhs.value, rhs.value) && deepEqualsApi(lhs.descriptors, rhs.descriptors) && deepEqualsApi(lhs.properties, rhs.properties)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Characteristic")
    deepHashApi(value: uuid, hasher: &hasher)
    deepHashApi(value: value, hasher: &hasher)
    deepHashApi(value: descriptors, hasher: &hasher)
    deepHashApi(value: properties, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Descriptor: AttributeData {
  var uuid: String
  var value: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Descriptor? {
    let uuid = pigeonVar_list[0] as! String
    let value: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])

    return Descriptor(
      uuid: uuid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      value,
    ]
  }
  static func == (lhs: Descriptor, rhs: Descriptor) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.uuid, rhs.uuid) && deepEqualsApi(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Descriptor")
    deepHashApi(value: uuid, hasher: &hasher)
    deepHashApi(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CharacteristicProperty: Hashable {
  var broadcast: Bool
  var read: Bool
  var writeWithoutResponse: Bool
  var write: Bool
  var notify: Bool
  var indicate: Bool
  var authenticatedSignedWrites: Bool
  var extendedProperties: Bool
  var notifyEncryptionRequired: Bool
  var indicateEncryptionRequired: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CharacteristicProperty? {
    let broadcast = pigeonVar_list[0] as! Bool
    let read = pigeonVar_list[1] as! Bool
    let writeWithoutResponse = pigeonVar_list[2] as! Bool
    let write = pigeonVar_list[3] as! Bool
    let notify = pigeonVar_list[4] as! Bool
    let indicate = pigeonVar_list[5] as! Bool
    let authenticatedSignedWrites = pigeonVar_list[6] as! Bool
    let extendedProperties = pigeonVar_list[7] as! Bool
    let notifyEncryptionRequired = pigeonVar_list[8] as! Bool
    let indicateEncryptionRequired = pigeonVar_list[9] as! Bool

    return CharacteristicProperty(
      broadcast: broadcast,
      read: read,
      writeWithoutResponse: writeWithoutResponse,
      write: write,
      notify: notify,
      indicate: indicate,
      authenticatedSignedWrites: authenticatedSignedWrites,
      extendedProperties: extendedProperties,
      notifyEncryptionRequired: notifyEncryptionRequired,
      indicateEncryptionRequired: indicateEncryptionRequired
    )
  }
  func toList() -> [Any?] {
    return [
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ]
  }
  static func == (lhs: CharacteristicProperty, rhs: CharacteristicProperty) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.broadcast, rhs.broadcast) && deepEqualsApi(lhs.read, rhs.read) && deepEqualsApi(lhs.writeWithoutResponse, rhs.writeWithoutResponse) && deepEqualsApi(lhs.write, rhs.write) && deepEqualsApi(lhs.notify, rhs.notify) && deepEqualsApi(lhs.indicate, rhs.indicate) && deepEqualsApi(lhs.authenticatedSignedWrites, rhs.authenticatedSignedWrites) && deepEqualsApi(lhs.extendedProperties, rhs.extendedProperties) && deepEqualsApi(lhs.notifyEncryptionRequired, rhs.notifyEncryptionRequired) && deepEqualsApi(lhs.indicateEncryptionRequired, rhs.indicateEncryptionRequired)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CharacteristicProperty")
    deepHashApi(value: broadcast, hasher: &hasher)
    deepHashApi(value: read, hasher: &hasher)
    deepHashApi(value: writeWithoutResponse, hasher: &hasher)
    deepHashApi(value: write, hasher: &hasher)
    deepHashApi(value: notify, hasher: &hasher)
    deepHashApi(value: indicate, hasher: &hasher)
    deepHashApi(value: authenticatedSignedWrites, hasher: &hasher)
    deepHashApi(value: extendedProperties, hasher: &hasher)
    deepHashApi(value: notifyEncryptionRequired, hasher: &hasher)
    deepHashApi(value: indicateEncryptionRequired, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CharacteristicPermission: Hashable {
  var readable: Bool
  var writeable: Bool
  var readEncryptionRequired: Bool
  var writeEncryptionRequired: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CharacteristicPermission? {
    let readable = pigeonVar_list[0] as! Bool
    let writeable = pigeonVar_list[1] as! Bool
    let readEncryptionRequired = pigeonVar_list[2] as! Bool
    let writeEncryptionRequired = pigeonVar_list[3] as! Bool

    return CharacteristicPermission(
      readable: readable,
      writeable: writeable,
      readEncryptionRequired: readEncryptionRequired,
      writeEncryptionRequired: writeEncryptionRequired
    )
  }
  func toList() -> [Any?] {
    return [
      readable,
      writeable,
      readEncryptionRequired,
      writeEncryptionRequired,
    ]
  }
  static func == (lhs: CharacteristicPermission, rhs: CharacteristicPermission) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.readable, rhs.readable) && deepEqualsApi(lhs.writeable, rhs.writeable) && deepEqualsApi(lhs.readEncryptionRequired, rhs.readEncryptionRequired) && deepEqualsApi(lhs.writeEncryptionRequired, rhs.writeEncryptionRequired)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CharacteristicPermission")
    deepHashApi(value: readable, hasher: &hasher)
    deepHashApi(value: writeable, hasher: &hasher)
    deepHashApi(value: readEncryptionRequired, hasher: &hasher)
    deepHashApi(value: writeEncryptionRequired, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttRequest: Hashable {
  var requestId: Int64
  var centralIdentifier: String
  var characteristicUuid: String
  var serviceUuid: String
  var offset: Int64
  var value: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttRequest? {
    let requestId = pigeonVar_list[0] as! Int64
    let centralIdentifier = pigeonVar_list[1] as! String
    let characteristicUuid = pigeonVar_list[2] as! String
    let serviceUuid = pigeonVar_list[3] as! String
    let offset = pigeonVar_list[4] as! Int64
    let value: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[5])

    return AttRequest(
      requestId: requestId,
      centralIdentifier: centralIdentifier,
      characteristicUuid: characteristicUuid,
      serviceUuid: serviceUuid,
      offset: offset,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      centralIdentifier,
      characteristicUuid,
      serviceUuid,
      offset,
      value,
    ]
  }
  static func == (lhs: AttRequest, rhs: AttRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.requestId, rhs.requestId) && deepEqualsApi(lhs.centralIdentifier, rhs.centralIdentifier) && deepEqualsApi(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsApi(lhs.offset, rhs.offset) && deepEqualsApi(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttRequest")
    deepHashApi(value: requestId, hasher: &hasher)
    deepHashApi(value: centralIdentifier, hasher: &hasher)
    deepHashApi(value: characteristicUuid, hasher: &hasher)
    deepHashApi(value: serviceUuid, hasher: &hasher)
    deepHashApi(value: offset, hasher: &hasher)
    deepHashApi(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MutableDescriptor: Hashable {
  var uuid: String
  var value: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MutableDescriptor? {
    let uuid = pigeonVar_list[0] as! String
    let value: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])

    return MutableDescriptor(
      uuid: uuid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      value,
    ]
  }
  static func == (lhs: MutableDescriptor, rhs: MutableDescriptor) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.uuid, rhs.uuid) && deepEqualsApi(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MutableDescriptor")
    deepHashApi(value: uuid, hasher: &hasher)
    deepHashApi(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MutableCharacteristic: Hashable {
  var uuid: String
  var properties: CharacteristicProperty? = nil
  var permissions: CharacteristicPermission? = nil
  var value: FlutterStandardTypedData? = nil
  var descriptors: [MutableDescriptor?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MutableCharacteristic? {
    let uuid = pigeonVar_list[0] as! String
    let properties: CharacteristicProperty? = nilOrValue(pigeonVar_list[1])
    let permissions: CharacteristicPermission? = nilOrValue(pigeonVar_list[2])
    let value: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])
    let descriptors: [MutableDescriptor?]? = nilOrValue(pigeonVar_list[4])

    return MutableCharacteristic(
      uuid: uuid,
      properties: properties,
      permissions: permissions,
      value: value,
      descriptors: descriptors
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      properties,
      permissions,
      value,
      descriptors,
    ]
  }
  static func == (lhs: MutableCharacteristic, rhs: MutableCharacteristic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.uuid, rhs.uuid) && deepEqualsApi(lhs.properties, rhs.properties) && deepEqualsApi(lhs.permissions, rhs.permissions) && deepEqualsApi(lhs.value, rhs.value) && deepEqualsApi(lhs.descriptors, rhs.descriptors)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MutableCharacteristic")
    deepHashApi(value: uuid, hasher: &hasher)
    deepHashApi(value: properties, hasher: &hasher)
    deepHashApi(value: permissions, hasher: &hasher)
    deepHashApi(value: value, hasher: &hasher)
    deepHashApi(value: descriptors, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MutableService: Hashable {
  var uuid: String
  var isPrimary: Bool
  var characteristics: [MutableCharacteristic?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MutableService? {
    let uuid = pigeonVar_list[0] as! String
    let isPrimary = pigeonVar_list[1] as! Bool
    let characteristics = pigeonVar_list[2] as! [MutableCharacteristic?]

    return MutableService(
      uuid: uuid,
      isPrimary: isPrimary,
      characteristics: characteristics
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      isPrimary,
      characteristics,
    ]
  }
  static func == (lhs: MutableService, rhs: MutableService) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsApi(lhs.uuid, rhs.uuid) && deepEqualsApi(lhs.isPrimary, rhs.isPrimary) && deepEqualsApi(lhs.characteristics, rhs.characteristics)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MutableService")
    deepHashApi(value: uuid, hasher: &hasher)
    deepHashApi(value: isPrimary, hasher: &hasher)
    deepHashApi(value: characteristics, hasher: &hasher)
  }
}

private class ApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ClientState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AttResult(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return ClientSession.fromList(self.readValue() as! [Any?])
    case 133:
      return PeripheralSession.fromList(self.readValue() as! [Any?])
    case 134:
      return PeripheralManagerSession.fromList(self.readValue() as! [Any?])
    case 135:
      return Peripheral.fromList(self.readValue() as! [Any?])
    case 136:
      return AdvertisementData.fromList(self.readValue() as! [Any?])
    case 137:
      return ScanResult.fromList(self.readValue() as! [Any?])
    case 138:
      return Service.fromList(self.readValue() as! [Any?])
    case 139:
      return Characteristic.fromList(self.readValue() as! [Any?])
    case 140:
      return Descriptor.fromList(self.readValue() as! [Any?])
    case 141:
      return CharacteristicProperty.fromList(self.readValue() as! [Any?])
    case 142:
      return CharacteristicPermission.fromList(self.readValue() as! [Any?])
    case 143:
      return AttRequest.fromList(self.readValue() as! [Any?])
    case 144:
      return MutableDescriptor.fromList(self.readValue() as! [Any?])
    case 145:
      return MutableCharacteristic.fromList(self.readValue() as! [Any?])
    case 146:
      return MutableService.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ClientState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConnectionState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AttResult {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ClientSession {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PeripheralSession {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PeripheralManagerSession {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? Peripheral {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AdvertisementData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ScanResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? Service {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? Characteristic {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? Descriptor {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicProperty {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicPermission {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? AttRequest {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? MutableDescriptor {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? MutableCharacteristic {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? MutableService {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ApiPigeonCodecWriter(data: data)
  }
}

class ApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ApiPigeonCodec(readerWriter: ApiPigeonCodecReaderWriter())
}


/// The APIs that are used to communicate from the flutter plugin to the
/// host platform.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ButaneHostApi {
  /// "Central" APIs.
  func state(session: ClientSession?, completion: @escaping (Result<ClientState, Error>) -> Void)
  /// Scans for peripherals that are advertising services.
  func scan(session: ClientSession?, forServices: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelScan(session: ClientSession?, completion: @escaping (Result<Void, Error>) -> Void)
  /// A list of known peripherals optionally filtered by their identifiers.
  func peripherals(session: ClientSession?, peripheralIdentifiers: [String], completion: @escaping (Result<[Peripheral], Error>) -> Void)
  /// A list of connected peripherals identified by an offered service.
  func connectedPeripherals(session: ClientSession?, serviceUuids: [String], completion: @escaping (Result<[Peripheral], Error>) -> Void)
  /// Establishes a connection to the peripheral.
  func connect(session: PeripheralSession, completion: @escaping (Result<Void, Error>) -> Void)
  /// Cancels an active or pending connection to the peripheral.
  func cancelConnection(session: PeripheralSession, completion: @escaping (Result<Void, Error>) -> Void)
  func connectionState(session: PeripheralSession, completion: @escaping (Result<ConnectionState, Error>) -> Void)
  /// Discovers services offered by the peripheral.
  func discoverServices(session: PeripheralSession, serviceUuids: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func services(session: PeripheralSession, completion: @escaping (Result<[Service], Error>) -> Void)
  /// Discovers characteristics offered by the service.
  func discoverCharacteristics(session: PeripheralSession, serviceUuid: String, characteristicUuids: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func characteristics(session: PeripheralSession, serviceUuid: String, completion: @escaping (Result<[Characteristic], Error>) -> Void)
  /// Reads the value of the characteristic.
  func readCharacteristic(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Writes the value of the characteristic.
  func writeCharacteristic(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, value: FlutterStandardTypedData, withoutResponse: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func observeCharacteristic(observe: Bool, session: PeripheralSession, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Reads the value of the descriptor.
  func readDescriptor(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, descriptorUuid: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Writes the value of the descriptor.
  func writeDescriptor(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, descriptorUuid: String, value: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Requests a read of the RSSI for the peripheral.
  func readRssi(session: PeripheralSession, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Requests a target ATT MTU and returns the negotiated/effective ATT MTU.
  ///
  /// A platform without a client-side request ignores the target and reports
  /// its effective value.
  func requestMtu(session: PeripheralSession, mtu: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  /// "Peripheral" APIs.
  func peripheralManagerState(session: PeripheralManagerSession, completion: @escaping (Result<ClientState, Error>) -> Void)
  func startAdvertising(session: PeripheralManagerSession, localName: String?, serviceUuids: [String]?, completion: @escaping (Result<Void, Error>) -> Void)
  func stopAdvertising(session: PeripheralManagerSession, completion: @escaping (Result<Void, Error>) -> Void)
  func addService(session: PeripheralManagerSession, service: MutableService, completion: @escaping (Result<Void, Error>) -> Void)
  func removeService(session: PeripheralManagerSession, serviceUuid: String, completion: @escaping (Result<Void, Error>) -> Void)
  func removeAllServices(session: PeripheralManagerSession, completion: @escaping (Result<Void, Error>) -> Void)
  func respondToRequest(session: PeripheralManagerSession, requestId: Int64, result: AttResult, value: FlutterStandardTypedData?, completion: @escaping (Result<Void, Error>) -> Void)
  func updateValue(session: PeripheralManagerSession, serviceUuid: String, characteristicUuid: String, value: FlutterStandardTypedData, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ButaneHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ApiPigeonCodec.shared }
  /// Sets up an instance of `ButaneHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ButaneHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// "Central" APIs.
    let stateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.state\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg: ClientSession? = nilOrValue(args[0])
        api.state(session: sessionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stateChannel.setMessageHandler(nil)
    }
    /// Scans for peripherals that are advertising services.
    let scanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.scan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg: ClientSession? = nilOrValue(args[0])
        let forServicesArg: [String]? = nilOrValue(args[1])
        api.scan(session: sessionArg, forServices: forServicesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanChannel.setMessageHandler(nil)
    }
    let cancelScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg: ClientSession? = nilOrValue(args[0])
        api.cancelScan(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelScanChannel.setMessageHandler(nil)
    }
    /// A list of known peripherals optionally filtered by their identifiers.
    let peripheralsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripherals\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      peripheralsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg: ClientSession? = nilOrValue(args[0])
        let peripheralIdentifiersArg = args[1] as! [String]
        api.peripherals(session: sessionArg, peripheralIdentifiers: peripheralIdentifiersArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      peripheralsChannel.setMessageHandler(nil)
    }
    /// A list of connected peripherals identified by an offered service.
    let connectedPeripheralsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectedPeripherals\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectedPeripheralsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg: ClientSession? = nilOrValue(args[0])
        let serviceUuidsArg = args[1] as! [String]
        api.connectedPeripherals(session: sessionArg, serviceUuids: serviceUuidsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectedPeripheralsChannel.setMessageHandler(nil)
    }
    /// Establishes a connection to the peripheral.
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        api.connect(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    /// Cancels an active or pending connection to the peripheral.
    let cancelConnectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelConnection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelConnectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        api.cancelConnection(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelConnectionChannel.setMessageHandler(nil)
    }
    let connectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        api.connectionState(session: sessionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectionStateChannel.setMessageHandler(nil)
    }
    /// Discovers services offered by the peripheral.
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidsArg: [String]? = nilOrValue(args[1])
        api.discoverServices(session: sessionArg, serviceUuids: serviceUuidsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let servicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.services\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      servicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        api.services(session: sessionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      servicesChannel.setMessageHandler(nil)
    }
    /// Discovers characteristics offered by the service.
    let discoverCharacteristicsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverCharacteristics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverCharacteristicsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidArg = args[1] as! String
        let characteristicUuidsArg: [String]? = nilOrValue(args[2])
        api.discoverCharacteristics(session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuids: characteristicUuidsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverCharacteristicsChannel.setMessageHandler(nil)
    }
    let characteristicsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.characteristics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      characteristicsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidArg = args[1] as! String
        api.characteristics(session: sessionArg, serviceUuid: serviceUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      characteristicsChannel.setMessageHandler(nil)
    }
    /// Reads the value of the characteristic.
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.readCharacteristic(session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    /// Writes the value of the characteristic.
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let valueArg = args[3] as! FlutterStandardTypedData
        let withoutResponseArg = args[4] as! Bool
        api.writeCharacteristic(session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, value: valueArg, withoutResponse: withoutResponseArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    let observeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.observeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      observeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let observeArg = args[0] as! Bool
        let sessionArg = args[1] as! PeripheralSession
        let serviceUuidArg = args[2] as! String
        let characteristicUuidArg = args[3] as! String
        api.observeCharacteristic(observe: observeArg, session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      observeCharacteristicChannel.setMessageHandler(nil)
    }
    /// Reads the value of the descriptor.
    let readDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let descriptorUuidArg = args[3] as! String
        api.readDescriptor(session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, descriptorUuid: descriptorUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readDescriptorChannel.setMessageHandler(nil)
    }
    /// Writes the value of the descriptor.
    let writeDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let descriptorUuidArg = args[3] as! String
        let valueArg = args[4] as! FlutterStandardTypedData
        api.writeDescriptor(session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, descriptorUuid: descriptorUuidArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeDescriptorChannel.setMessageHandler(nil)
    }
    /// Requests a read of the RSSI for the peripheral.
    let readRssiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readRssi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRssiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        api.readRssi(session: sessionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRssiChannel.setMessageHandler(nil)
    }
    /// Requests a target ATT MTU and returns the negotiated/effective ATT MTU.
    ///
    /// A platform without a client-side request ignores the target and reports
    /// its effective value.
    let requestMtuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.requestMtu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestMtuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralSession
        let mtuArg = args[1] as! Int64
        api.requestMtu(session: sessionArg, mtu: mtuArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestMtuChannel.setMessageHandler(nil)
    }
    /// "Peripheral" APIs.
    let peripheralManagerStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripheralManagerState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      peripheralManagerStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        api.peripheralManagerState(session: sessionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      peripheralManagerStateChannel.setMessageHandler(nil)
    }
    let startAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.startAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAdvertisingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        let localNameArg: String? = nilOrValue(args[1])
        let serviceUuidsArg: [String]? = nilOrValue(args[2])
        api.startAdvertising(session: sessionArg, localName: localNameArg, serviceUuids: serviceUuidsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAdvertisingChannel.setMessageHandler(nil)
    }
    let stopAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.stopAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAdvertisingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        api.stopAdvertising(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopAdvertisingChannel.setMessageHandler(nil)
    }
    let addServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.addService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addServiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        let serviceArg = args[1] as! MutableService
        api.addService(session: sessionArg, service: serviceArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addServiceChannel.setMessageHandler(nil)
    }
    let removeServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.removeService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeServiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        let serviceUuidArg = args[1] as! String
        api.removeService(session: sessionArg, serviceUuid: serviceUuidArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeServiceChannel.setMessageHandler(nil)
    }
    let removeAllServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.removeAllServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAllServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        api.removeAllServices(session: sessionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAllServicesChannel.setMessageHandler(nil)
    }
    let respondToRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.respondToRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondToRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        let requestIdArg = args[1] as! Int64
        let resultArg = args[2] as! AttResult
        let valueArg: FlutterStandardTypedData? = nilOrValue(args[3])
        api.respondToRequest(session: sessionArg, requestId: requestIdArg, result: resultArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondToRequestChannel.setMessageHandler(nil)
    }
    let updateValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.updateValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! PeripheralManagerSession
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let valueArg = args[3] as! FlutterStandardTypedData
        api.updateValue(session: sessionArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, value: valueArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateValueChannel.setMessageHandler(nil)
    }
  }
}
/// The APIs that are used from the host platform to communicate with the
/// flutter plugin.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ButaneFlutterApiProtocol {
  /// "Central Client" APIs.
  func onClientState(clientIdentifier clientIdentifierArg: String?, state stateArg: ClientState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanResult(scanResult scanResultArg: ScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// "Peripheral" APIs.
  func onConnectionState(peripheral peripheralArg: Peripheral, state stateArg: ConnectionState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCharacteristicValue(peripheral peripheralArg: Peripheral, characteristic characteristicArg: Characteristic, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDescriptorValue(peripheral peripheralArg: Peripheral, descriptor descriptorArg: Descriptor, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// "Peripheral Manager" APIs.
  func onPeripheralManagerState(clientIdentifier clientIdentifierArg: String?, state stateArg: ClientState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onServiceAdded(serviceUuid serviceUuidArg: String, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onReadRequest(request requestArg: AttRequest, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWriteRequests(requests requestsArg: [AttRequest], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCentralSubscribed(clientIdentifier clientIdentifierArg: String?, centralIdentifier centralIdentifierArg: String, serviceUuid serviceUuidArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCentralUnsubscribed(clientIdentifier clientIdentifierArg: String?, centralIdentifier centralIdentifierArg: String, serviceUuid serviceUuidArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onReadyToUpdateSubscribers(clientIdentifier clientIdentifierArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ButaneFlutterApi: ButaneFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ApiPigeonCodec {
    return ApiPigeonCodec.shared
  }
  /// "Central Client" APIs.
  func onClientState(clientIdentifier clientIdentifierArg: String?, state stateArg: ClientState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdentifierArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanResult(scanResult scanResultArg: ScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([scanResultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// "Peripheral" APIs.
  func onConnectionState(peripheral peripheralArg: Peripheral, state stateArg: ConnectionState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCharacteristicValue(peripheral peripheralArg: Peripheral, characteristic characteristicArg: Characteristic, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, characteristicArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDescriptorValue(peripheral peripheralArg: Peripheral, descriptor descriptorArg: Descriptor, value valueArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peripheralArg, descriptorArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// "Peripheral Manager" APIs.
  func onPeripheralManagerState(clientIdentifier clientIdentifierArg: String?, state stateArg: ClientState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onPeripheralManagerState\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdentifierArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onServiceAdded(serviceUuid serviceUuidArg: String, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onServiceAdded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([serviceUuidArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onReadRequest(request requestArg: AttRequest, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onReadRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onWriteRequests(requests requestsArg: [AttRequest], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onWriteRequests\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCentralSubscribed(clientIdentifier clientIdentifierArg: String?, centralIdentifier centralIdentifierArg: String, serviceUuid serviceUuidArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCentralSubscribed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdentifierArg, centralIdentifierArg, serviceUuidArg, characteristicUuidArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCentralUnsubscribed(clientIdentifier clientIdentifierArg: String?, centralIdentifier centralIdentifierArg: String, serviceUuid serviceUuidArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCentralUnsubscribed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdentifierArg, centralIdentifierArg, serviceUuidArg, characteristicUuidArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onReadyToUpdateSubscribers(clientIdentifier clientIdentifierArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onReadyToUpdateSubscribers\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdentifierArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
