name: butane_android
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/nicholasspencer/butane
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  butane_platform_interface:
    path: ../butane_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nicospencer.butane_android
        pluginClass: ButaneAndroidPlugin
