name: butane_android
description: "Android implementation of Butane Bluetooth Low Energy for Flutter applications."
version: 0.1.0
homepage: https://github.com/nicholasspencer/butane
repository: https://github.com/nicholasspencer/butane_flutter
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  butane_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    implements: butane_platform_interface
    platforms:
      android:
        package: com.nicospencer.butane_android
        pluginClass: ButaneAndroidPlugin
        dartPluginClass: ButaneAndroid
