// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_API_GEN_H_
#define PIGEON_API_GEN_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace butane_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class ClientState {
  kUnknown = 0,
  kResetting = 1,
  kUnsupported = 2,
  kUnauthorized = 3,
  kPoweredOff = 4,
  kPoweredOn = 5
};

enum class ConnectionState {
  kDisconnected = 0,
  kConnecting = 1,
  kReconnecting = 2,
  kConnected = 3,
  kDisconnecting = 4
};

enum class AttResult {
  kSuccess = 0,
  kInvalidHandle = 1,
  kReadNotPermitted = 2,
  kWriteNotPermitted = 3,
  kInvalidOffset = 4,
  kAttributeNotFound = 5,
  kUnlikelyError = 6
};


// A unique identifier for a peripheral coupled with the [adapterIdentifier] and
// [clientIdentifier] that discovered it.
//
// The [clientIdentifier] is the identifier of the client that discovered the
// peripheral. This is useful when multiple clients are connected to the same
// adapter. If omitted, the default client is used.
//
// The [adapterIdentifier] is the identifier of the adapter that discovered the
// peripheral. This is useful when multiple adapters are available on the same
// device. If omitted, the default adapter is used.
//
// Generated class from Pigeon that represents data sent in messages.
class ClientSession {
 public:
  // Constructs an object setting all non-nullable fields.
  ClientSession();

  // Constructs an object setting all fields.
  explicit ClientSession(
    const std::string* peripheral_identifier,
    const std::string* client_identifier,
    const std::string* adapter_identifier,
    const std::string* restoration_identifier);

  const std::string* peripheral_identifier() const;
  void set_peripheral_identifier(const std::string_view* value_arg);
  void set_peripheral_identifier(std::string_view value_arg);

  const std::string* client_identifier() const;
  void set_client_identifier(const std::string_view* value_arg);
  void set_client_identifier(std::string_view value_arg);

  const std::string* adapter_identifier() const;
  void set_adapter_identifier(const std::string_view* value_arg);
  void set_adapter_identifier(std::string_view value_arg);

  const std::string* restoration_identifier() const;
  void set_restoration_identifier(const std::string_view* value_arg);
  void set_restoration_identifier(std::string_view value_arg);

 private:
  static ClientSession FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> peripheral_identifier_;
  std::optional<std::string> client_identifier_;
  std::optional<std::string> adapter_identifier_;
  std::optional<std::string> restoration_identifier_;
};


// Generated class from Pigeon that represents data sent in messages.
class PeripheralSession {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PeripheralSession(const std::string& peripheral_identifier);

  // Constructs an object setting all fields.
  explicit PeripheralSession(
    const std::string& peripheral_identifier,
    const std::string* client_identifier,
    const std::string* adapter_identifier,
    const std::string* restoration_identifier);

  const std::string& peripheral_identifier() const;
  void set_peripheral_identifier(std::string_view value_arg);

  const std::string* client_identifier() const;
  void set_client_identifier(const std::string_view* value_arg);
  void set_client_identifier(std::string_view value_arg);

  const std::string* adapter_identifier() const;
  void set_adapter_identifier(const std::string_view* value_arg);
  void set_adapter_identifier(std::string_view value_arg);

  const std::string* restoration_identifier() const;
  void set_restoration_identifier(const std::string_view* value_arg);
  void set_restoration_identifier(std::string_view value_arg);

 private:
  static PeripheralSession FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class Peripheral;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string peripheral_identifier_;
  std::optional<std::string> client_identifier_;
  std::optional<std::string> adapter_identifier_;
  std::optional<std::string> restoration_identifier_;
};


// Generated class from Pigeon that represents data sent in messages.
class PeripheralManagerSession {
 public:
  // Constructs an object setting all non-nullable fields.
  PeripheralManagerSession();

  // Constructs an object setting all fields.
  explicit PeripheralManagerSession(
    const std::string* client_identifier,
    const std::string* adapter_identifier,
    const std::string* restoration_identifier);

  const std::string* client_identifier() const;
  void set_client_identifier(const std::string_view* value_arg);
  void set_client_identifier(std::string_view value_arg);

  const std::string* adapter_identifier() const;
  void set_adapter_identifier(const std::string_view* value_arg);
  void set_adapter_identifier(std::string_view value_arg);

  const std::string* restoration_identifier() const;
  void set_restoration_identifier(const std::string_view* value_arg);
  void set_restoration_identifier(std::string_view value_arg);

 private:
  static PeripheralManagerSession FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> client_identifier_;
  std::optional<std::string> adapter_identifier_;
  std::optional<std::string> restoration_identifier_;
};


// Generated class from Pigeon that represents data sent in messages.
class Peripheral {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit Peripheral(
    const PeripheralSession& session,
    const ConnectionState& state);

  // Constructs an object setting all fields.
  explicit Peripheral(
    const PeripheralSession& session,
    const std::string* name,
    const int64_t* rssi,
    const ConnectionState& state);

  ~Peripheral() = default;
  Peripheral(const Peripheral& other);
  Peripheral& operator=(const Peripheral& other);
  Peripheral(Peripheral&& other) = default;
  Peripheral& operator=(Peripheral&& other) noexcept = default;
  const PeripheralSession& session() const;
  void set_session(const PeripheralSession& value_arg);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const int64_t* rssi() const;
  void set_rssi(const int64_t* value_arg);
  void set_rssi(int64_t value_arg);

  const ConnectionState& state() const;
  void set_state(const ConnectionState& value_arg);

 private:
  static Peripheral FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ScanResult;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<PeripheralSession> session_;
  std::optional<std::string> name_;
  std::optional<int64_t> rssi_;
  ConnectionState state_;
};


// Generated class from Pigeon that represents data sent in messages.
class AdvertisementData {
 public:
  // Constructs an object setting all non-nullable fields.
  AdvertisementData();

  // Constructs an object setting all fields.
  explicit AdvertisementData(
    const std::string* local_name,
    const std::vector<uint8_t>* manufacturer_data,
    const flutter::EncodableList* service_uuids,
    const flutter::EncodableMap* service_data,
    const int64_t* tx_power_level,
    const bool* is_connectable);

  const std::string* local_name() const;
  void set_local_name(const std::string_view* value_arg);
  void set_local_name(std::string_view value_arg);

  const std::vector<uint8_t>* manufacturer_data() const;
  void set_manufacturer_data(const std::vector<uint8_t>* value_arg);
  void set_manufacturer_data(const std::vector<uint8_t>& value_arg);

  const flutter::EncodableList* service_uuids() const;
  void set_service_uuids(const flutter::EncodableList* value_arg);
  void set_service_uuids(const flutter::EncodableList& value_arg);

  const flutter::EncodableMap* service_data() const;
  void set_service_data(const flutter::EncodableMap* value_arg);
  void set_service_data(const flutter::EncodableMap& value_arg);

  const int64_t* tx_power_level() const;
  void set_tx_power_level(const int64_t* value_arg);
  void set_tx_power_level(int64_t value_arg);

  const bool* is_connectable() const;
  void set_is_connectable(const bool* value_arg);
  void set_is_connectable(bool value_arg);

 private:
  static AdvertisementData FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ScanResult;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> local_name_;
  std::optional<std::vector<uint8_t>> manufacturer_data_;
  std::optional<flutter::EncodableList> service_uuids_;
  std::optional<flutter::EncodableMap> service_data_;
  std::optional<int64_t> tx_power_level_;
  std::optional<bool> is_connectable_;
};


// Generated class from Pigeon that represents data sent in messages.
class ScanResult {
 public:
  // Constructs an object setting all fields.
  explicit ScanResult(
    const Peripheral& peripheral,
    const AdvertisementData& advertisement_data);

  ~ScanResult() = default;
  ScanResult(const ScanResult& other);
  ScanResult& operator=(const ScanResult& other);
  ScanResult(ScanResult&& other) = default;
  ScanResult& operator=(ScanResult&& other) noexcept = default;
  const Peripheral& peripheral() const;
  void set_peripheral(const Peripheral& value_arg);

  const AdvertisementData& advertisement_data() const;
  void set_advertisement_data(const AdvertisementData& value_arg);

 private:
  static ScanResult FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<Peripheral> peripheral_;
  std::unique_ptr<AdvertisementData> advertisement_data_;
};


// Generated class from Pigeon that represents data sent in messages.
class Service {
 public:
  // Constructs an object setting all fields.
  explicit Service(
    const std::string& uuid,
    bool is_primary);

  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  bool is_primary() const;
  void set_is_primary(bool value_arg);

 private:
  static Service FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  bool is_primary_;
};


// Generated class from Pigeon that represents data sent in messages.
class CharacteristicProperty;

class Characteristic {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit Characteristic(const std::string& uuid);

  // Constructs an object setting all fields.
  explicit Characteristic(
    const std::string& uuid,
    const std::vector<uint8_t>* value,
    const flutter::EncodableList* descriptors,
    const CharacteristicProperty* properties);

  ~Characteristic() = default;
  Characteristic(const Characteristic& other);
  Characteristic& operator=(const Characteristic& other);
  Characteristic(Characteristic&& other) = default;
  Characteristic& operator=(Characteristic&& other) noexcept = default;
  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  const std::vector<uint8_t>* value() const;
  void set_value(const std::vector<uint8_t>* value_arg);
  void set_value(const std::vector<uint8_t>& value_arg);

  const flutter::EncodableList* descriptors() const;
  void set_descriptors(const flutter::EncodableList* value_arg);
  void set_descriptors(const flutter::EncodableList& value_arg);

  const CharacteristicProperty* properties() const;
  void set_properties(const CharacteristicProperty* value_arg);
  void set_properties(const CharacteristicProperty& value_arg);

 private:
  static Characteristic FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  std::optional<std::vector<uint8_t>> value_;
  std::optional<flutter::EncodableList> descriptors_;
  std::unique_ptr<CharacteristicProperty> properties_;
};


// Generated class from Pigeon that represents data sent in messages.
class Descriptor {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit Descriptor(const std::string& uuid);

  // Constructs an object setting all fields.
  explicit Descriptor(
    const std::string& uuid,
    const std::vector<uint8_t>* value);

  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  const std::vector<uint8_t>* value() const;
  void set_value(const std::vector<uint8_t>* value_arg);
  void set_value(const std::vector<uint8_t>& value_arg);

 private:
  static Descriptor FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  std::optional<std::vector<uint8_t>> value_;
};


// Generated class from Pigeon that represents data sent in messages.
class CharacteristicProperty {
 public:
  // Constructs an object setting all fields.
  explicit CharacteristicProperty(
    bool broadcast,
    bool read,
    bool write_without_response,
    bool write,
    bool notify,
    bool indicate,
    bool authenticated_signed_writes,
    bool extended_properties,
    bool notify_encryption_required,
    bool indicate_encryption_required);

  bool broadcast() const;
  void set_broadcast(bool value_arg);

  bool read() const;
  void set_read(bool value_arg);

  bool write_without_response() const;
  void set_write_without_response(bool value_arg);

  bool write() const;
  void set_write(bool value_arg);

  bool notify() const;
  void set_notify(bool value_arg);

  bool indicate() const;
  void set_indicate(bool value_arg);

  bool authenticated_signed_writes() const;
  void set_authenticated_signed_writes(bool value_arg);

  bool extended_properties() const;
  void set_extended_properties(bool value_arg);

  bool notify_encryption_required() const;
  void set_notify_encryption_required(bool value_arg);

  bool indicate_encryption_required() const;
  void set_indicate_encryption_required(bool value_arg);

 private:
  static CharacteristicProperty FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class Characteristic;
  friend class MutableCharacteristic;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  bool broadcast_;
  bool read_;
  bool write_without_response_;
  bool write_;
  bool notify_;
  bool indicate_;
  bool authenticated_signed_writes_;
  bool extended_properties_;
  bool notify_encryption_required_;
  bool indicate_encryption_required_;
};


// Generated class from Pigeon that represents data sent in messages.
class CharacteristicPermission {
 public:
  // Constructs an object setting all fields.
  explicit CharacteristicPermission(
    bool readable,
    bool writeable,
    bool read_encryption_required,
    bool write_encryption_required);

  bool readable() const;
  void set_readable(bool value_arg);

  bool writeable() const;
  void set_writeable(bool value_arg);

  bool read_encryption_required() const;
  void set_read_encryption_required(bool value_arg);

  bool write_encryption_required() const;
  void set_write_encryption_required(bool value_arg);

 private:
  static CharacteristicPermission FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class MutableCharacteristic;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  bool readable_;
  bool writeable_;
  bool read_encryption_required_;
  bool write_encryption_required_;
};


// Generated class from Pigeon that represents data sent in messages.
class AttRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit AttRequest(
    int64_t request_id,
    const std::string& central_identifier,
    const std::string& characteristic_uuid,
    const std::string& service_uuid,
    int64_t offset);

  // Constructs an object setting all fields.
  explicit AttRequest(
    int64_t request_id,
    const std::string& central_identifier,
    const std::string& characteristic_uuid,
    const std::string& service_uuid,
    int64_t offset,
    const std::vector<uint8_t>* value);

  int64_t request_id() const;
  void set_request_id(int64_t value_arg);

  const std::string& central_identifier() const;
  void set_central_identifier(std::string_view value_arg);

  const std::string& characteristic_uuid() const;
  void set_characteristic_uuid(std::string_view value_arg);

  const std::string& service_uuid() const;
  void set_service_uuid(std::string_view value_arg);

  int64_t offset() const;
  void set_offset(int64_t value_arg);

  const std::vector<uint8_t>* value() const;
  void set_value(const std::vector<uint8_t>* value_arg);
  void set_value(const std::vector<uint8_t>& value_arg);

 private:
  static AttRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t request_id_;
  std::string central_identifier_;
  std::string characteristic_uuid_;
  std::string service_uuid_;
  int64_t offset_;
  std::optional<std::vector<uint8_t>> value_;
};


// Generated class from Pigeon that represents data sent in messages.
class MutableDescriptor {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MutableDescriptor(const std::string& uuid);

  // Constructs an object setting all fields.
  explicit MutableDescriptor(
    const std::string& uuid,
    const std::vector<uint8_t>* value);

  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  const std::vector<uint8_t>* value() const;
  void set_value(const std::vector<uint8_t>* value_arg);
  void set_value(const std::vector<uint8_t>& value_arg);

 private:
  static MutableDescriptor FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  std::optional<std::vector<uint8_t>> value_;
};


// Generated class from Pigeon that represents data sent in messages.
class MutableCharacteristic {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MutableCharacteristic(const std::string& uuid);

  // Constructs an object setting all fields.
  explicit MutableCharacteristic(
    const std::string& uuid,
    const CharacteristicProperty* properties,
    const CharacteristicPermission* permissions,
    const std::vector<uint8_t>* value,
    const flutter::EncodableList* descriptors);

  ~MutableCharacteristic() = default;
  MutableCharacteristic(const MutableCharacteristic& other);
  MutableCharacteristic& operator=(const MutableCharacteristic& other);
  MutableCharacteristic(MutableCharacteristic&& other) = default;
  MutableCharacteristic& operator=(MutableCharacteristic&& other) noexcept = default;
  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  const CharacteristicProperty* properties() const;
  void set_properties(const CharacteristicProperty* value_arg);
  void set_properties(const CharacteristicProperty& value_arg);

  const CharacteristicPermission* permissions() const;
  void set_permissions(const CharacteristicPermission* value_arg);
  void set_permissions(const CharacteristicPermission& value_arg);

  const std::vector<uint8_t>* value() const;
  void set_value(const std::vector<uint8_t>* value_arg);
  void set_value(const std::vector<uint8_t>& value_arg);

  const flutter::EncodableList* descriptors() const;
  void set_descriptors(const flutter::EncodableList* value_arg);
  void set_descriptors(const flutter::EncodableList& value_arg);

 private:
  static MutableCharacteristic FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  std::unique_ptr<CharacteristicProperty> properties_;
  std::unique_ptr<CharacteristicPermission> permissions_;
  std::optional<std::vector<uint8_t>> value_;
  std::optional<flutter::EncodableList> descriptors_;
};


// Generated class from Pigeon that represents data sent in messages.
class MutableService {
 public:
  // Constructs an object setting all fields.
  explicit MutableService(
    const std::string& uuid,
    bool is_primary,
    const flutter::EncodableList& characteristics);

  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  bool is_primary() const;
  void set_is_primary(bool value_arg);

  const flutter::EncodableList& characteristics() const;
  void set_characteristics(const flutter::EncodableList& value_arg);

 private:
  static MutableService FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ButaneHostApi;
  friend class ButaneFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  bool is_primary_;
  flutter::EncodableList characteristics_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// The APIs that are used to communicate from the flutter plugin to the
// host platform.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class ButaneHostApi {
 public:
  ButaneHostApi(const ButaneHostApi&) = delete;
  ButaneHostApi& operator=(const ButaneHostApi&) = delete;
  virtual ~ButaneHostApi() {}
  // "Central" APIs.
  virtual void State(
    const ClientSession* session,
    std::function<void(ErrorOr<ClientState> reply)> result) = 0;
  // Scans for peripherals that are advertising services.
  virtual void Scan(
    const ClientSession* session,
    const flutter::EncodableList* for_services,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void CancelScan(
    const ClientSession* session,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // A list of known peripherals optionally filtered by their identifiers.
  virtual void Peripherals(
    const ClientSession* session,
    const flutter::EncodableList& peripheral_identifiers,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // A list of connected peripherals identified by an offered service.
  virtual void ConnectedPeripherals(
    const ClientSession* session,
    const flutter::EncodableList& service_uuids,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Establishes a connection to the peripheral.
  virtual void Connect(
    const PeripheralSession& session,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Cancels an active or pending connection to the peripheral.
  virtual void CancelConnection(
    const PeripheralSession& session,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ConnectionState(
    const PeripheralSession& session,
    std::function<void(ErrorOr<::butane_windows::ConnectionState> reply)> result) = 0;
  // Discovers services offered by the peripheral.
  virtual void DiscoverServices(
    const PeripheralSession& session,
    const flutter::EncodableList* service_uuids,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Services(
    const PeripheralSession& session,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Discovers characteristics offered by the service.
  virtual void DiscoverCharacteristics(
    const PeripheralSession& session,
    const std::string& service_uuid,
    const flutter::EncodableList* characteristic_uuids,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Characteristics(
    const PeripheralSession& session,
    const std::string& service_uuid,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Reads the value of the characteristic.
  virtual void ReadCharacteristic(
    const PeripheralSession& session,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;
  // Writes the value of the characteristic.
  virtual void WriteCharacteristic(
    const PeripheralSession& session,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    const std::vector<uint8_t>& value,
    bool without_response,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ObserveCharacteristic(
    bool observe,
    const PeripheralSession& session,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Reads the value of the descriptor.
  virtual void ReadDescriptor(
    const PeripheralSession& session,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    const std::string& descriptor_uuid,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;
  // Writes the value of the descriptor.
  virtual void WriteDescriptor(
    const PeripheralSession& session,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    const std::string& descriptor_uuid,
    const std::vector<uint8_t>& value,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Requests a read of the RSSI for the peripheral.
  virtual void ReadRssi(
    const PeripheralSession& session,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Requests a MTU size change.
  virtual void RequestMtu(
    const PeripheralSession& session,
    int64_t mtu,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // "Peripheral" APIs.
  virtual void PeripheralManagerState(
    const PeripheralManagerSession& session,
    std::function<void(ErrorOr<ClientState> reply)> result) = 0;
  virtual void StartAdvertising(
    const PeripheralManagerSession& session,
    const std::string* local_name,
    const flutter::EncodableList* service_uuids,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void StopAdvertising(
    const PeripheralManagerSession& session,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void AddService(
    const PeripheralManagerSession& session,
    const MutableService& service,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void RemoveService(
    const PeripheralManagerSession& session,
    const std::string& service_uuid,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void RemoveAllServices(
    const PeripheralManagerSession& session,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void RespondToRequest(
    const PeripheralManagerSession& session,
    int64_t request_id,
    const AttResult& request_result,
    const std::vector<uint8_t>* value,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void UpdateValue(
    const PeripheralManagerSession& session,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    const std::vector<uint8_t>& value,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by ButaneHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `ButaneHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    ButaneHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    ButaneHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  ButaneHostApi() = default;
};
// The APIs that are used from the host platform to communicate with the
// flutter plugin.
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class ButaneFlutterApi {
 public:
  ButaneFlutterApi(flutter::BinaryMessenger* binary_messenger);
  ButaneFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  // "Central Client" APIs.
  void OnClientState(
    const std::string* client_identifier,
    const ClientState& state,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnScanResult(
    const ScanResult& scan_result,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // "Peripheral" APIs.
  void OnConnectionState(
    const Peripheral& peripheral,
    const ConnectionState& state,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCharacteristicValue(
    const Peripheral& peripheral,
    const Characteristic& characteristic,
    const std::vector<uint8_t>& value,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDescriptorValue(
    const Peripheral& peripheral,
    const Descriptor& descriptor,
    const std::vector<uint8_t>& value,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // "Peripheral Manager" APIs.
  void OnPeripheralManagerState(
    const std::string* client_identifier,
    const ClientState& state,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnServiceAdded(
    const std::string& service_uuid,
    const std::string* error,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnReadRequest(
    const AttRequest& request,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnWriteRequests(
    const flutter::EncodableList& requests,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCentralSubscribed(
    const std::string* client_identifier,
    const std::string& central_identifier,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCentralUnsubscribed(
    const std::string* client_identifier,
    const std::string& central_identifier,
    const std::string& service_uuid,
    const std::string& characteristic_uuid,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnReadyToUpdateSubscribers(
    const std::string* client_identifier,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace butane_windows
#endif  // PIGEON_API_GEN_H_
