name: butane_platform_interface
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/nicholasspencer/butane
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.0
  uuid: ^4.0.0

dev_dependencies:
  test: ^1.0.0
  flutter_lints: ^3.0.0
  build_runner: ^2.12.2
  pigeon: ^26.2.3

flutter:
