include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas

analyzer:
  exclude:
    - "**.g.dart"
  errors:
    require_trailing_commas: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
