// Autogenerated from Pigeon (v15.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class PeripheralData {
  PeripheralData({
    this.identifier,
    this.name,
  });

  String? identifier;

  String? name;

  Object encode() {
    return <Object?>[
      identifier,
      name,
    ];
  }

  static PeripheralData decode(Object result) {
    result as List<Object?>;
    return PeripheralData(
      identifier: result[0] as String?,
      name: result[1] as String?,
    );
  }
}

class ServiceData {
  ServiceData({
    this.isPrimary,
  });

  bool? isPrimary;

  Object encode() {
    return <Object?>[
      isPrimary,
    ];
  }

  static ServiceData decode(Object result) {
    result as List<Object?>;
    return ServiceData(
      isPrimary: result[0] as bool?,
    );
  }
}

class CharacteristicData {
  CharacteristicData({
    this.value,
    this.descriptors,
    this.properties,
  });

  /// List of bytes
  List<int?>? value;

  List<DescriptorData?>? descriptors;

  CharacteristicProperty? properties;

  Object encode() {
    return <Object?>[
      value,
      descriptors,
      properties?.encode(),
    ];
  }

  static CharacteristicData decode(Object result) {
    result as List<Object?>;
    return CharacteristicData(
      value: (result[0] as List<Object?>?)?.cast<int?>(),
      descriptors: (result[1] as List<Object?>?)?.cast<DescriptorData?>(),
      properties: result[2] != null
          ? CharacteristicProperty.decode(result[2]! as List<Object?>)
          : null,
    );
  }
}

class DescriptorData {
  DescriptorData({
    this.value,
  });

  /// List of bytes
  List<int?>? value;

  Object encode() {
    return <Object?>[
      value,
    ];
  }

  static DescriptorData decode(Object result) {
    result as List<Object?>;
    return DescriptorData(
      value: (result[0] as List<Object?>?)?.cast<int?>(),
    );
  }
}

class CharacteristicProperty {
  CharacteristicProperty({
    this.broadcast = false,
    this.read = false,
    this.writeWithoutResponse = false,
    this.write = false,
    this.notify = false,
    this.indicate = false,
    this.authenticatedSignedWrites = false,
    this.extendedProperties = false,
    this.notifyEncryptionRequired = false,
    this.indicateEncryptionRequired = false,
  });

  bool broadcast;

  bool read;

  bool writeWithoutResponse;

  bool write;

  bool notify;

  bool indicate;

  bool authenticatedSignedWrites;

  bool extendedProperties;

  bool notifyEncryptionRequired;

  bool indicateEncryptionRequired;

  Object encode() {
    return <Object?>[
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    ];
  }

  static CharacteristicProperty decode(Object result) {
    result as List<Object?>;
    return CharacteristicProperty(
      broadcast: result[0]! as bool,
      read: result[1]! as bool,
      writeWithoutResponse: result[2]! as bool,
      write: result[3]! as bool,
      notify: result[4]! as bool,
      indicate: result[5]! as bool,
      authenticatedSignedWrites: result[6]! as bool,
      extendedProperties: result[7]! as bool,
      notifyEncryptionRequired: result[8]! as bool,
      indicateEncryptionRequired: result[9]! as bool,
    );
  }
}

class _ButaneApiCodec extends StandardMessageCodec {
  const _ButaneApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CharacteristicData) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is CharacteristicData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CharacteristicProperty) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is DescriptorData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PeripheralData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PeripheralData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ServiceData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is ServiceData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CharacteristicData.decode(readValue(buffer)!);
      case 129: 
        return CharacteristicData.decode(readValue(buffer)!);
      case 130: 
        return CharacteristicProperty.decode(readValue(buffer)!);
      case 131: 
        return DescriptorData.decode(readValue(buffer)!);
      case 132: 
        return PeripheralData.decode(readValue(buffer)!);
      case 133: 
        return PeripheralData.decode(readValue(buffer)!);
      case 134: 
        return ServiceData.decode(readValue(buffer)!);
      case 135: 
        return ServiceData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ButaneApi {
  /// Constructor for [ButaneApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ButaneApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _ButaneApiCodec();

  /// "Central" APIs.
  /// Scans for peripherals that are advertising services.
  Future<void> scan({List<String?> forServices = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.scan';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[forServices]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// A list of known peripherals optionally filtered by their identifiers.
  Future<List<PeripheralData?>> peripherals({List<String?> identifiers = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.peripherals';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[identifiers]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PeripheralData?>();
    }
  }

  /// Establishes a connection to the peripheral.
  Future<void> connect({required PeripheralData peripheral}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.connect';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[peripheral]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Cancels an active or pending connection to the peripheral.
  Future<void> cancelConnection({required PeripheralData peripheral}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.cancelConnection';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[peripheral]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// A list of connected peripherals identified by an offered service.
  Future<List<PeripheralData?>> connectedPeripherals({List<String?> services = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.connectedPeripherals';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[services]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<PeripheralData?>();
    }
  }

  /// Discovers services offered by the peripheral.
  Future<List<ServiceData?>> discoverServices({required PeripheralData peripheral, List<String?> serviceUuids = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.discoverServices';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[peripheral, serviceUuids]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<ServiceData?>();
    }
  }

  /// Discovers characteristics offered by the service.
  Future<List<CharacteristicData?>> discoverCharacteristics({required ServiceData service, List<String?> characteristicUuids = const []}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.discoverCharacteristics';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[service, characteristicUuids]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<CharacteristicData?>();
    }
  }

  /// Reads the value of the characteristic.
  Future<List<int?>> readCharacteristic({required CharacteristicData characteristic}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.readCharacteristic';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[characteristic]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<int?>();
    }
  }

  /// Writes the value of the characteristic.
  Future<void> writeCharacteristic({required CharacteristicData characteristic, required List<int?> value, bool withoutResponse = false,}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.writeCharacteristic';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[characteristic, value, withoutResponse]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Enables notifications or indications for the characteristic.
  Future<void> setNotification({required CharacteristicData characteristic, required bool enabled}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.setNotification';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[characteristic, enabled]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Reads the value of the descriptor.
  Future<List<int?>> readDescriptor({required DescriptorData descriptor}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.readDescriptor';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[descriptor]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<int?>();
    }
  }

  /// Writes the value of the descriptor.
  Future<void> writeDescriptor({required DescriptorData descriptor, required List<int?> value}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.writeDescriptor';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[descriptor, value]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Requests a read of the RSSI for the peripheral.
  Future<int> readRssi({required PeripheralData peripheral}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.readRssi';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[peripheral]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Requests a MTU size change.
  Future<int> requestMtu({required PeripheralData peripheral, required int mtu}) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.butane_platform_interface.ButaneApi.requestMtu';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[peripheral, mtu]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }
}
