// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ClientState(val raw: Int) {
  UNKNOWN(0),
  RESETTING(1),
  UNSUPPORTED(2),
  UNAUTHORIZED(3),
  POWERED_OFF(4),
  POWERED_ON(5);

  companion object {
    fun ofRaw(raw: Int): ClientState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ConnectionState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  RECONNECTING(2),
  CONNECTED(3),
  DISCONNECTING(4);

  companion object {
    fun ofRaw(raw: Int): ConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AttResult(val raw: Int) {
  SUCCESS(0),
  INVALID_HANDLE(1),
  READ_NOT_PERMITTED(2),
  WRITE_NOT_PERMITTED(3),
  INVALID_OFFSET(4),
  ATTRIBUTE_NOT_FOUND(5),
  UNLIKELY_ERROR(6);

  companion object {
    fun ofRaw(raw: Int): AttResult? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A unique identifier for a peripheral coupled with the [adapterIdentifier] and
 * [clientIdentifier] that discovered it.
 *
 * The [clientIdentifier] is the identifier of the client that discovered the
 * peripheral. This is useful when multiple clients are connected to the same
 * adapter. If omitted, the default client is used.
 *
 * The [adapterIdentifier] is the identifier of the adapter that discovered the
 * peripheral. This is useful when multiple adapters are available on the same
 * device. If omitted, the default adapter is used.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClientSession (
  val peripheralIdentifier: String? = null,
  val clientIdentifier: String? = null,
  val adapterIdentifier: String? = null,
  val restorationIdentifier: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClientSession {
      val peripheralIdentifier = pigeonVar_list[0] as String?
      val clientIdentifier = pigeonVar_list[1] as String?
      val adapterIdentifier = pigeonVar_list[2] as String?
      val restorationIdentifier = pigeonVar_list[3] as String?
      return ClientSession(peripheralIdentifier, clientIdentifier, adapterIdentifier, restorationIdentifier)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ClientSession) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralSession (
  val peripheralIdentifier: String,
  val clientIdentifier: String? = null,
  val adapterIdentifier: String? = null,
  val restorationIdentifier: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralSession {
      val peripheralIdentifier = pigeonVar_list[0] as String
      val clientIdentifier = pigeonVar_list[1] as String?
      val adapterIdentifier = pigeonVar_list[2] as String?
      val restorationIdentifier = pigeonVar_list[3] as String?
      return PeripheralSession(peripheralIdentifier, clientIdentifier, adapterIdentifier, restorationIdentifier)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peripheralIdentifier,
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralSession) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralManagerSession (
  val clientIdentifier: String? = null,
  val adapterIdentifier: String? = null,
  val restorationIdentifier: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralManagerSession {
      val clientIdentifier = pigeonVar_list[0] as String?
      val adapterIdentifier = pigeonVar_list[1] as String?
      val restorationIdentifier = pigeonVar_list[2] as String?
      return PeripheralManagerSession(clientIdentifier, adapterIdentifier, restorationIdentifier)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientIdentifier,
      adapterIdentifier,
      restorationIdentifier,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralManagerSession) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Peripheral (
  val session: PeripheralSession,
  val name: String? = null,
  val rssi: Long? = null,
  val state: ConnectionState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Peripheral {
      val session = pigeonVar_list[0] as PeripheralSession
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long?
      val state = pigeonVar_list[3] as ConnectionState
      return Peripheral(session, name, rssi, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      session,
      name,
      rssi,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Peripheral) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AdvertisementData (
  val localName: String? = null,
  val manufacturerData: ByteArray? = null,
  val serviceUuids: List<String?>? = null,
  val serviceData: Map<String?, ByteArray?>? = null,
  val txPowerLevel: Long? = null,
  val isConnectable: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdvertisementData {
      val localName = pigeonVar_list[0] as String?
      val manufacturerData = pigeonVar_list[1] as ByteArray?
      val serviceUuids = pigeonVar_list[2] as List<String?>?
      val serviceData = pigeonVar_list[3] as Map<String?, ByteArray?>?
      val txPowerLevel = pigeonVar_list[4] as Long?
      val isConnectable = pigeonVar_list[5] as Boolean?
      return AdvertisementData(localName, manufacturerData, serviceUuids, serviceData, txPowerLevel, isConnectable)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      localName,
      manufacturerData,
      serviceUuids,
      serviceData,
      txPowerLevel,
      isConnectable,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AdvertisementData) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanResult (
  val peripheral: Peripheral,
  val advertisementData: AdvertisementData
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanResult {
      val peripheral = pigeonVar_list[0] as Peripheral
      val advertisementData = pigeonVar_list[1] as AdvertisementData
      return ScanResult(peripheral, advertisementData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peripheral,
      advertisementData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ScanResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Service (
  val uuid: String,
  val isPrimary: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Service {
      val uuid = pigeonVar_list[0] as String
      val isPrimary = pigeonVar_list[1] as Boolean
      return Service(uuid, isPrimary)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      isPrimary,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Service) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Characteristic (
  val uuid: String,
  val value: ByteArray? = null,
  val descriptors: List<Descriptor?>? = null,
  val properties: CharacteristicProperty? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Characteristic {
      val uuid = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as ByteArray?
      val descriptors = pigeonVar_list[2] as List<Descriptor?>?
      val properties = pigeonVar_list[3] as CharacteristicProperty?
      return Characteristic(uuid, value, descriptors, properties)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      value,
      descriptors,
      properties,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Characteristic) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Descriptor (
  val uuid: String,
  val value: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Descriptor {
      val uuid = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as ByteArray?
      return Descriptor(uuid, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Descriptor) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CharacteristicProperty (
  val broadcast: Boolean,
  val read: Boolean,
  val writeWithoutResponse: Boolean,
  val write: Boolean,
  val notify: Boolean,
  val indicate: Boolean,
  val authenticatedSignedWrites: Boolean,
  val extendedProperties: Boolean,
  val notifyEncryptionRequired: Boolean,
  val indicateEncryptionRequired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CharacteristicProperty {
      val broadcast = pigeonVar_list[0] as Boolean
      val read = pigeonVar_list[1] as Boolean
      val writeWithoutResponse = pigeonVar_list[2] as Boolean
      val write = pigeonVar_list[3] as Boolean
      val notify = pigeonVar_list[4] as Boolean
      val indicate = pigeonVar_list[5] as Boolean
      val authenticatedSignedWrites = pigeonVar_list[6] as Boolean
      val extendedProperties = pigeonVar_list[7] as Boolean
      val notifyEncryptionRequired = pigeonVar_list[8] as Boolean
      val indicateEncryptionRequired = pigeonVar_list[9] as Boolean
      return CharacteristicProperty(broadcast, read, writeWithoutResponse, write, notify, indicate, authenticatedSignedWrites, extendedProperties, notifyEncryptionRequired, indicateEncryptionRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      broadcast,
      read,
      writeWithoutResponse,
      write,
      notify,
      indicate,
      authenticatedSignedWrites,
      extendedProperties,
      notifyEncryptionRequired,
      indicateEncryptionRequired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CharacteristicProperty) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CharacteristicPermission (
  val readable: Boolean,
  val writeable: Boolean,
  val readEncryptionRequired: Boolean,
  val writeEncryptionRequired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CharacteristicPermission {
      val readable = pigeonVar_list[0] as Boolean
      val writeable = pigeonVar_list[1] as Boolean
      val readEncryptionRequired = pigeonVar_list[2] as Boolean
      val writeEncryptionRequired = pigeonVar_list[3] as Boolean
      return CharacteristicPermission(readable, writeable, readEncryptionRequired, writeEncryptionRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      readable,
      writeable,
      readEncryptionRequired,
      writeEncryptionRequired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CharacteristicPermission) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttRequest (
  val requestId: Long,
  val centralIdentifier: String,
  val characteristicUuid: String,
  val serviceUuid: String,
  val offset: Long,
  val value: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttRequest {
      val requestId = pigeonVar_list[0] as Long
      val centralIdentifier = pigeonVar_list[1] as String
      val characteristicUuid = pigeonVar_list[2] as String
      val serviceUuid = pigeonVar_list[3] as String
      val offset = pigeonVar_list[4] as Long
      val value = pigeonVar_list[5] as ByteArray?
      return AttRequest(requestId, centralIdentifier, characteristicUuid, serviceUuid, offset, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      centralIdentifier,
      characteristicUuid,
      serviceUuid,
      offset,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AttRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MutableDescriptor (
  val uuid: String,
  val value: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MutableDescriptor {
      val uuid = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as ByteArray?
      return MutableDescriptor(uuid, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MutableDescriptor) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MutableCharacteristic (
  val uuid: String,
  val properties: CharacteristicProperty? = null,
  val permissions: CharacteristicPermission? = null,
  val value: ByteArray? = null,
  val descriptors: List<MutableDescriptor?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MutableCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as CharacteristicProperty?
      val permissions = pigeonVar_list[2] as CharacteristicPermission?
      val value = pigeonVar_list[3] as ByteArray?
      val descriptors = pigeonVar_list[4] as List<MutableDescriptor?>?
      return MutableCharacteristic(uuid, properties, permissions, value, descriptors)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      permissions,
      value,
      descriptors,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MutableCharacteristic) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MutableService (
  val uuid: String,
  val isPrimary: Boolean,
  val characteristics: List<MutableCharacteristic?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MutableService {
      val uuid = pigeonVar_list[0] as String
      val isPrimary = pigeonVar_list[1] as Boolean
      val characteristics = pigeonVar_list[2] as List<MutableCharacteristic?>
      return MutableService(uuid, isPrimary, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      isPrimary,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MutableService) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ClientState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AttResult.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClientSession.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralSession.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralManagerSession.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Peripheral.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdvertisementData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanResult.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Service.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Characteristic.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Descriptor.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CharacteristicProperty.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CharacteristicPermission.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttRequest.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MutableDescriptor.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MutableCharacteristic.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MutableService.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ClientState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ConnectionState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AttResult -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ClientSession -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PeripheralSession -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PeripheralManagerSession -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is Peripheral -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is AdvertisementData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ScanResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is Service -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is Characteristic -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is Descriptor -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CharacteristicProperty -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is CharacteristicPermission -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is AttRequest -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is MutableDescriptor -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is MutableCharacteristic -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is MutableService -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * The APIs that are used to communicate from the flutter plugin to the
 * host platform.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ButaneHostApi {
  /** "Central" APIs. */
  fun state(session: ClientSession?, callback: (Result<ClientState>) -> Unit)
  /** Scans for peripherals that are advertising services. */
  fun scan(session: ClientSession?, forServices: List<String>?, callback: (Result<Unit>) -> Unit)
  fun cancelScan(session: ClientSession?, callback: (Result<Unit>) -> Unit)
  /** A list of known peripherals optionally filtered by their identifiers. */
  fun peripherals(session: ClientSession?, peripheralIdentifiers: List<String>, callback: (Result<List<Peripheral>>) -> Unit)
  /** A list of connected peripherals identified by an offered service. */
  fun connectedPeripherals(session: ClientSession?, serviceUuids: List<String>, callback: (Result<List<Peripheral>>) -> Unit)
  /** Establishes a connection to the peripheral. */
  fun connect(session: PeripheralSession, callback: (Result<Unit>) -> Unit)
  /** Cancels an active or pending connection to the peripheral. */
  fun cancelConnection(session: PeripheralSession, callback: (Result<Unit>) -> Unit)
  fun connectionState(session: PeripheralSession, callback: (Result<ConnectionState>) -> Unit)
  /** Discovers services offered by the peripheral. */
  fun discoverServices(session: PeripheralSession, serviceUuids: List<String>?, callback: (Result<Unit>) -> Unit)
  fun services(session: PeripheralSession, callback: (Result<List<Service>>) -> Unit)
  /** Discovers characteristics offered by the service. */
  fun discoverCharacteristics(session: PeripheralSession, serviceUuid: String, characteristicUuids: List<String>?, callback: (Result<Unit>) -> Unit)
  fun characteristics(session: PeripheralSession, serviceUuid: String, callback: (Result<List<Characteristic>>) -> Unit)
  /** Reads the value of the characteristic. */
  fun readCharacteristic(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, callback: (Result<ByteArray>) -> Unit)
  /** Writes the value of the characteristic. */
  fun writeCharacteristic(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, value: ByteArray, withoutResponse: Boolean, callback: (Result<Unit>) -> Unit)
  fun observeCharacteristic(observe: Boolean, session: PeripheralSession, serviceUuid: String, characteristicUuid: String, callback: (Result<Unit>) -> Unit)
  /** Reads the value of the descriptor. */
  fun readDescriptor(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, descriptorUuid: String, callback: (Result<ByteArray>) -> Unit)
  /** Writes the value of the descriptor. */
  fun writeDescriptor(session: PeripheralSession, serviceUuid: String, characteristicUuid: String, descriptorUuid: String, value: ByteArray, callback: (Result<Unit>) -> Unit)
  /** Requests a read of the RSSI for the peripheral. */
  fun readRssi(session: PeripheralSession, callback: (Result<Long>) -> Unit)
  /** Requests a MTU size change. */
  fun requestMtu(session: PeripheralSession, mtu: Long, callback: (Result<Long>) -> Unit)
  /** "Peripheral" APIs. */
  fun peripheralManagerState(session: PeripheralManagerSession, callback: (Result<ClientState>) -> Unit)
  fun startAdvertising(session: PeripheralManagerSession, localName: String?, serviceUuids: List<String>?, callback: (Result<Unit>) -> Unit)
  fun stopAdvertising(session: PeripheralManagerSession, callback: (Result<Unit>) -> Unit)
  fun addService(session: PeripheralManagerSession, service: MutableService, callback: (Result<Unit>) -> Unit)
  fun removeService(session: PeripheralManagerSession, serviceUuid: String, callback: (Result<Unit>) -> Unit)
  fun removeAllServices(session: PeripheralManagerSession, callback: (Result<Unit>) -> Unit)
  fun respondToRequest(session: PeripheralManagerSession, requestId: Long, requestResult: AttResult, value: ByteArray?, callback: (Result<Unit>) -> Unit)
  fun updateValue(session: PeripheralManagerSession, serviceUuid: String, characteristicUuid: String, value: ByteArray, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by ButaneHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
    /** Sets up an instance of `ButaneHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ButaneHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.state$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as ClientSession?
            api.state(sessionArg) { result: Result<ClientState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.scan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as ClientSession?
            val forServicesArg = args[1] as List<String>?
            api.scan(sessionArg, forServicesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as ClientSession?
            api.cancelScan(sessionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripherals$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as ClientSession?
            val peripheralIdentifiersArg = args[1] as List<String>
            api.peripherals(sessionArg, peripheralIdentifiersArg) { result: Result<List<Peripheral>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectedPeripherals$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as ClientSession?
            val serviceUuidsArg = args[1] as List<String>
            api.connectedPeripherals(sessionArg, serviceUuidsArg) { result: Result<List<Peripheral>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            api.connect(sessionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.cancelConnection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            api.cancelConnection(sessionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.connectionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            api.connectionState(sessionArg) { result: Result<ConnectionState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidsArg = args[1] as List<String>?
            api.discoverServices(sessionArg, serviceUuidsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.services$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            api.services(sessionArg) { result: Result<List<Service>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.discoverCharacteristics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidArg = args[1] as String
            val characteristicUuidsArg = args[2] as List<String>?
            api.discoverCharacteristics(sessionArg, serviceUuidArg, characteristicUuidsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.characteristics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidArg = args[1] as String
            api.characteristics(sessionArg, serviceUuidArg) { result: Result<List<Characteristic>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.readCharacteristic(sessionArg, serviceUuidArg, characteristicUuidArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val valueArg = args[3] as ByteArray
            val withoutResponseArg = args[4] as Boolean
            api.writeCharacteristic(sessionArg, serviceUuidArg, characteristicUuidArg, valueArg, withoutResponseArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.observeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val observeArg = args[0] as Boolean
            val sessionArg = args[1] as PeripheralSession
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            api.observeCharacteristic(observeArg, sessionArg, serviceUuidArg, characteristicUuidArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readDescriptor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val descriptorUuidArg = args[3] as String
            api.readDescriptor(sessionArg, serviceUuidArg, characteristicUuidArg, descriptorUuidArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.writeDescriptor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val descriptorUuidArg = args[3] as String
            val valueArg = args[4] as ByteArray
            api.writeDescriptor(sessionArg, serviceUuidArg, characteristicUuidArg, descriptorUuidArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.readRssi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            api.readRssi(sessionArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.requestMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralSession
            val mtuArg = args[1] as Long
            api.requestMtu(sessionArg, mtuArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.peripheralManagerState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            api.peripheralManagerState(sessionArg) { result: Result<ClientState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.startAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            val localNameArg = args[1] as String?
            val serviceUuidsArg = args[2] as List<String>?
            api.startAdvertising(sessionArg, localNameArg, serviceUuidsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.stopAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            api.stopAdvertising(sessionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.addService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            val serviceArg = args[1] as MutableService
            api.addService(sessionArg, serviceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.removeService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            val serviceUuidArg = args[1] as String
            api.removeService(sessionArg, serviceUuidArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.removeAllServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            api.removeAllServices(sessionArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.respondToRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            val requestIdArg = args[1] as Long
            val requestResultArg = args[2] as AttResult
            val valueArg = args[3] as ByteArray?
            api.respondToRequest(sessionArg, requestIdArg, requestResultArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.butane_platform_interface.ButaneHostApi.updateValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as PeripheralManagerSession
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val valueArg = args[3] as ByteArray
            api.updateValue(sessionArg, serviceUuidArg, characteristicUuidArg, valueArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * The APIs that are used from the host platform to communicate with the
 * flutter plugin.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ButaneFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ButaneFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
  }
  /** "Central Client" APIs. */
  fun onClientState(clientIdentifierArg: String?, stateArg: ClientState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onClientState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdentifierArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanResult(scanResultArg: ScanResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(scanResultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** "Peripheral" APIs. */
  fun onConnectionState(peripheralArg: Peripheral, stateArg: ConnectionState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onConnectionState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCharacteristicValue(peripheralArg: Peripheral, characteristicArg: Characteristic, valueArg: ByteArray, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCharacteristicValue$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralArg, characteristicArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDescriptorValue(peripheralArg: Peripheral, descriptorArg: Descriptor, valueArg: ByteArray, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onDescriptorValue$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peripheralArg, descriptorArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** "Peripheral Manager" APIs. */
  fun onPeripheralManagerState(clientIdentifierArg: String?, stateArg: ClientState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onPeripheralManagerState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdentifierArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onServiceAdded(serviceUuidArg: String, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onServiceAdded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(serviceUuidArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onReadRequest(requestArg: AttRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onReadRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onWriteRequests(requestsArg: List<AttRequest>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onWriteRequests$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCentralSubscribed(clientIdentifierArg: String?, centralIdentifierArg: String, serviceUuidArg: String, characteristicUuidArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCentralSubscribed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdentifierArg, centralIdentifierArg, serviceUuidArg, characteristicUuidArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCentralUnsubscribed(clientIdentifierArg: String?, centralIdentifierArg: String, serviceUuidArg: String, characteristicUuidArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onCentralUnsubscribed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdentifierArg, centralIdentifierArg, serviceUuidArg, characteristicUuidArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onReadyToUpdateSubscribers(clientIdentifierArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.butane_platform_interface.ButaneFlutterApi.onReadyToUpdateSubscribers$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdentifierArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
